export const groups=[
 ["开始之前",[["intro","本站目的"],["how","如何使用本站"],["plan","学习规划"]]],
 ["基础工具",[["tools","学习工具"],["accounting","会计基础"],["math","数学与统计"]]],
 ["经济学基础",[["micro","微观经济学"],["macro","宏观经济学"],["econometrics","计量经济学"]]],
 ["金融学核心",[["corporate","公司金融"],["investments","投资学"],["pricing","资产定价"],["fixed-income","固定收益"]]],
 ["市场、机构与风险",[["valuation","企业研究与估值"],["derivatives","衍生品与金融工程"],["market-structure","市场微观结构与算法交易"],["risk","风险管理"],["private-markets","私募股权与风险投资"]]],
 ["数据与计算金融",[["empirical","实证金融"],["quant","量化研究"],["ml-finance","金融机器学习与另类数据"]]],
 ["金融科技与前沿",[["fintech","金融科技、支付与开放金融"],["digital-assets","数字资产与区块链金融"],["climate-finance","气候金融与可持续投资"],["financial-stability","金融稳定与宏观审慎监管"]]],
 ["研究与实践",[["macro-research","宏观与政策研究"],["behavioral","行为金融"],["projects","研究方法与项目"],["books","书单与资源"]]]
] as const;
type Res={name:string,url:string,level:string,kind?:string,pre?:string,description?:string};
const R=(name:string,url:string,level:string,kind="公开课",pre="具备上一阶段的基础知识",description?:string):Res=>({name,url,level,kind,pre,description});
export const topics:Record<string,{title:string,intro:string;resources:Res[]}>= {
 tools:{title:"学习工具",intro:"用稳定的工作流整理资料、处理数据并复现研究。",resources:[R("Obsidian","https://obsidian.md/","入门","工具","无需前置"),R("Zotero","https://www.zotero.org/","入门","工具","无需前置"),R("Python","https://www.python.org/","进阶","工具","基础编程")]},
 accounting:{title:"会计基础",intro:"从三张报表理解企业经营活动如何转化为财务数字。",resources:[R("OpenStax Financial Accounting","https://openstax.org/details/books/principles-financial-accounting","入门","开放教材","基础代数"),R("MIT 15.515 Financial Accounting","https://ocw.mit.edu/courses/15-515-financial-accounting-fall-2003/","进阶"),R("MIT 15.535 Business Analysis","https://ocw.mit.edu/courses/15-535-business-analysis-using-financial-statements-spring-2003/","高级")]},
 math:{title:"数学与统计",intro:"建立理解经济模型、风险与定价所需的共同语言。",resources:[R("MIT 18.01 Calculus","https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/","入门"),R("MIT 18.06 Linear Algebra","https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/","进阶"),R("MIT 18.650 Statistics","https://ocw.mit.edu/courses/18-650-statistics-for-applications-fall-2016/","高级")]},
 micro:{title:"微观经济学",intro:"研究个人、企业与市场如何在约束下做出选择。",resources:[R("MIT 14.01SC Principles of Microeconomics","https://ocw.mit.edu/courses/14-01sc-principles-of-microeconomics-fall-2011/","入门"),R("MIT 14.04 Intermediate Microeconomics","https://ocw.mit.edu/courses/14-04-intermediate-microeconomic-theory-fall-2020/","进阶"),R("MIT 14.121 Microeconomic Theory I","https://ocw.mit.edu/courses/14-121-microeconomic-theory-i-fall-2015/","高级")]},
 macro:{title:"宏观经济学",intro:"理解增长、通胀、就业以及货币与财政政策。",resources:[R("MIT 14.02 Principles of Macroeconomics","https://ocw.mit.edu/courses/14-02-principles-of-macroeconomics-spring-2023/","入门"),R("MIT 14.06 Intermediate Macroeconomics","https://ocw.mit.edu/courses/14-06-intermediate-macroeconomic-theory-spring-2004/","进阶"),R("MIT 14.461 Advanced Macroeconomics","https://ocw.mit.edu/courses/14-461-advanced-macroeconomics-i-fall-2012/","高级")]},
 econometrics:{title:"计量经济学",intro:"把经济问题转化为可以使用数据检验的假设。",resources:[R("MIT 14.30 Statistical Methods","https://ocw.mit.edu/courses/14-30-introduction-to-statistical-methods-in-economics-spring-2009/","入门"),R("MIT 14.32 Econometrics","https://ocw.mit.edu/courses/14-32-econometrics-spring-2007/","进阶"),R("MIT 14.381 Statistical Method","https://ocw.mit.edu/courses/14-381-statistical-method-in-economics-fall-2018/","高级")]},
 corporate:{title:"公司金融",intro:"理解企业如何投资、融资、分配现金并管理风险。",resources:[R("OpenStax Principles of Finance","https://openstax.org/details/books/principles-finance","入门","开放教材"),R("Damodaran Corporate Finance","https://pages.stern.nyu.edu/~adamodar/New_Home_Page/cfshdesc.html","进阶"),R("MIT 15.402 Finance Theory II","https://ocw.mit.edu/courses/15-402-finance-theory-ii-spring-2003/","高级")]},
 investments:{title:"投资学",intro:"从风险与收益出发理解资产配置和市场运作。",resources:[R("Yale Financial Markets","https://oyc.yale.edu/economics/econ-252","入门"),R("MIT 15.401 Finance Theory I","https://ocw.mit.edu/courses/15-401-finance-theory-i-fall-2008/","进阶"),R("MIT 15.433 Investments","https://ocw.mit.edu/courses/15-433-investments-spring-2003/","高级")]},
 pricing:{title:"资产定价",intro:"研究风险为何以及如何获得补偿。",resources:[R("Yale Financial Theory","https://oyc.yale.edu/economics/econ-251","入门"),R("MIT 15.401 Finance Theory I","https://ocw.mit.edu/courses/15-401-finance-theory-i-fall-2008/","进阶"),R("Asset Pricing — John Cochrane","https://www.johnhcochrane.com/asset-pricing","高级","开放教材")]},
 "fixed-income":{title:"固定收益",intro:"理解债券、利率与信用风险的定价框架。",resources:[R("OpenStax Finance: Bonds","https://openstax.org/books/principles-finance/pages/10-why-it-matters","入门","开放教材"),R("MIT 15.401 Finance Theory I","https://ocw.mit.edu/courses/15-401-finance-theory-i-fall-2008/","进阶"),R("MIT 15.433 Investments","https://ocw.mit.edu/courses/15-433-investments-spring-2003/","高级")]},
 valuation:{title:"企业研究与估值",intro:"把会计、公司金融和行业知识用于研究真实企业。",resources:[R("OpenStax Finance: Valuation","https://openstax.org/books/principles-finance/pages/11-why-it-matters","入门","开放教材"),R("Damodaran Valuation","https://pages.stern.nyu.edu/~adamodar/New_Home_Page/equity.html","进阶"),R("MIT 15.535 Business Analysis","https://ocw.mit.edu/courses/15-535-business-analysis-using-financial-statements-spring-2003/","高级")]},
 derivatives:{title:"衍生品与金融工程",intro:"从期权、期货和互换出发，理解无套利定价、动态对冲以及复杂风险如何被拆解和管理。",resources:[R("MIT 15.401 — Options","https://ocw.mit.edu/courses/15-401-finance-theory-i-fall-2008/pages/video-lectures-and-slides/options/","入门","公开课","货币时间价值、概率与基础投资学","通过视频与讲义理解期权收益、复制组合、二项式模型和 Black–Scholes 的基本直觉。"),R("MIT 15.433 Investments","https://ocw.mit.edu/courses/15-433-investments-spring-2003/","进阶","公开课","投资学、统计与微积分","把期权、风险管理和投资组合放入统一的投资决策框架，并配合问题集练习。"),R("MIT 18.S096 Mathematics with Applications in Finance","https://ocw.mit.edu/courses/18-s096-topics-in-mathematics-with-applications-in-finance-fall-2013/","高级","公开课","多元微积分、线性代数、概率与 Python","使用随机模型、数值方法和计算实验研究衍生品定价与金融风险。") ]},
 "market-structure":{title:"市场微观结构与算法交易",intro:"研究订单如何形成价格、流动性如何产生，以及交易规则和自动化策略如何改变市场质量。",resources:[R("MIT 15.401 Finance Theory I","https://ocw.mit.edu/courses/15-401-finance-theory-i-fall-2008/","入门","公开课","投资学入门与基础统计","先建立市场、证券、风险收益与有效市场的共同框架，再进入交易机制。"),R("SEC Market Structure Analytics","https://www.sec.gov/featured-topics/market-structure-analytics","进阶","公开资料","市场基础、描述统计与数据可视化","使用监管机构公开指标研究点差、成交、订单执行和美国股票市场结构。"),R("Georgia Tech — Machine Learning for Trading","https://quantsoftware.gatech.edu/Machine_Learning_for_Trading_Course","高级","公开课","Python、概率统计、算法与投资学","用公开课程视频、讲义和代码学习市场数据处理、策略研究、回测与机器学习，并正视交易成本和过拟合。") ]},
 empirical:{title:"实证金融",intro:"使用真实数据检验关于市场、公司和投资者的假设。",resources:[R("Causal Inference: The Mixtape","https://mixtape.scunning.com/","入门","开放教材"),R("MIT 14.32 Econometrics","https://ocw.mit.edu/courses/14-32-econometrics-spring-2007/","进阶"),R("MIT 14.387 Applied Econometrics","https://ocw.mit.edu/courses/14-387-applied-econometrics-mostly-harmless-big-data-fall-2014/","高级")]},
 "macro-research":{title:"宏观与政策研究",intro:"把宏观理论与公开数据结合，解释经济和政策变化。",resources:[R("FRED Economic Data","https://fred.stlouisfed.org/","入门","公开资料"),R("MIT 14.06 Intermediate Macroeconomics","https://ocw.mit.edu/courses/14-06-intermediate-macroeconomic-theory-spring-2004/","进阶"),R("MIT 14.461 Advanced Macroeconomics","https://ocw.mit.edu/courses/14-461-advanced-macroeconomics-i-fall-2012/","高级")]},
 risk:{title:"风险管理",intro:"识别、度量并沟通市场、信用与流动性风险。",resources:[R("OpenStax Principles of Finance","https://openstax.org/details/books/principles-finance","入门","开放教材"),R("MIT 15.401 Finance Theory I","https://ocw.mit.edu/courses/15-401-finance-theory-i-fall-2008/","进阶"),R("MIT 18.S096 Mathematics in Finance","https://ocw.mit.edu/courses/18-s096-topics-in-mathematics-with-applications-in-finance-fall-2013/","高级")]},
 "private-markets":{title:"私募股权与风险投资",intro:"理解初创企业和非上市公司的融资、估值、契约、治理、基金运作与退出机制。",resources:[R("MIT 15.393 Nuts and Bolts of New Ventures","https://ocw.mit.edu/courses/15-393-nuts-and-bolts-of-new-ventures-january-iap-2025/","入门","公开课","公司金融基础","从创业者视角认识商业计划、融资过程、团队、法律与早期企业运营。"),R("MIT 15.391 Early Stage Capital","https://ocw.mit.edu/courses/15-391-early-stage-capital-fall-2010/","进阶","公开课","会计、公司金融与基础估值","学习天使投资、风险投资、融资条款和早期项目筛选，并分析真实商业案例。"),R("MIT 15.431 Entrepreneurial Finance","https://ocw.mit.edu/courses/15-431-entrepreneurial-finance-spring-2011/","高级","公开课","金融理论、估值与基础博弈论","系统研究创业融资、风险投资基金、契约设计、私募股权与退出决策。") ]},
 behavioral:{title:"行为金融",intro:"研究认知偏差、激励和制度如何影响金融决策。",resources:[R("Yale Financial Markets","https://oyc.yale.edu/economics/econ-252","入门"),R("Behavioral Corporate Finance Survey","https://www.nber.org/papers/w17333","进阶","论文"),R("MIT 14.13 Psychology and Economics","https://ocw.mit.edu/courses/14-13-psychology-and-economics-spring-2020/","高级")]},
 quant:{title:"量化研究",intro:"用编程、统计和可复现研究回答金融问题。",resources:[R("Python Data Science Handbook","https://jakevdp.github.io/PythonDataScienceHandbook/","入门","开放教材"),R("MIT 18.S096 Mathematics in Finance","https://ocw.mit.edu/courses/18-s096-topics-in-mathematics-with-applications-in-finance-fall-2013/","进阶"),R("MIT 15.433 Investments","https://ocw.mit.edu/courses/15-433-investments-spring-2003/","高级")]},
 "ml-finance":{title:"金融机器学习与另类数据",intro:"把机器学习用于文本、行情、披露与其他非传统数据，同时严格控制时间泄漏、过拟合和不可解释结论。",resources:[R("An Introduction to Statistical Learning","https://www.statlearning.com/","入门","开放教材","概率统计、线性代数与基础编程","免费教材配套课程视频和实验，先建立监督学习、正则化、树模型与模型评估的可靠基础。"),R("MIT 15.S08 FinTech: Shaping the Financial World","https://ocw.mit.edu/courses/15-s08-fintech-shaping-the-financial-world-spring-2020/","进阶","公开课","金融学核心、Python 与统计","了解人工智能、深度学习、开放 API 和自动化如何进入支付、信贷、交易与保险。"),R("Georgia Tech — Machine Learning for Trading","https://quantsoftware.gatech.edu/Machine_Learning_for_Trading_Course","高级","公开课","Python、概率统计、算法、投资学与回测基础","完成从金融数据处理、指标构造到机器学习策略评估的完整实践，重点避免样本外失效。") ]},
 fintech:{title:"金融科技、支付与开放金融",intro:"理解数字支付、平台信贷、开放银行、智能投顾和金融基础设施如何重塑金融服务与普惠金融。",resources:[R("MIT 15.S08 FinTech: Shaping the Financial World","https://ocw.mit.edu/courses/15-s08-fintech-shaping-the-financial-world-spring-2020/","入门","公开课","金融市场与互联网基础","覆盖支付、信贷、开放 API、智能投顾、保险科技和监管议题，是建立金融科技全景图的起点。"),R("BIS Innovation Hub","https://www.bis.org/about/innovation-hub/overview","进阶","公开资料","货币银行学、支付系统与基础编程","跟踪中央银行在支付、数字货币、监管科技和金融基础设施方面的实验与公开项目。"),R("MIT 14.129 Blockchain and the Design of Financial Systems","https://www.ocw.mit.edu/courses/14-129-blockchain-and-the-design-of-financial-systems-spring-2025/","高级","公开课","微观经济学、博弈论、金融学与区块链基础","把密码学系统与契约理论、机制设计、货币理论和监管结合，分析新型金融系统如何设计。") ]},
 "digital-assets":{title:"数字资产与区块链金融",intro:"从密码学、共识和激励机制出发，分析加密资产、稳定币、去中心化金融及其风险与监管。",resources:[R("Bitcoin and Cryptocurrency Technologies","https://bitcoinbook.cs.princeton.edu/","入门","开放教材","基础编程与概率直觉","Princeton 作者免费教材，从密码学、共识、挖矿和匿名性建立技术基础，避免只从价格理解数字资产。"),R("MIT 15.S12 Blockchain and Money","https://ocw.mit.edu/courses/15-s12-blockchain-and-money-fall-2018/","进阶","公开课","金融市场、货币银行学与区块链基础","通过完整视频和讲义研究区块链在支付、金融中介和公共政策中的应用与限制。"),R("MIT 14.129 Blockchain and the Design of Financial Systems","https://www.ocw.mit.edu/courses/14-129-blockchain-and-the-design-of-financial-systems-spring-2025/","高级","公开课","微观经济理论、机制设计、金融学与密码学","研究智能合约、去中心化机制、货币系统与监管之间的设计权衡。") ]},
 "climate-finance":{title:"气候金融与可持续投资",intro:"研究物理风险、转型风险和政策变化如何进入资产定价、企业融资、银行风险与长期投资决策。",resources:[R("IMF Climate Change Indicators Dashboard","https://data.imf.org/en/datasets/IMF.STA%3ACCI","入门","公开数据","宏观经济学与基础数据分析","从排放、能源、绿色金融和气候暴露指标开始，用真实数据提出可检验的问题。"),R("NGFS Climate Scenarios Portal","https://www.ngfs.net/ngfs-scenarios-portal/explore/","进阶","项目平台","宏观经济、风险管理与情景分析","比较不同有序转型、无序转型和高升温情景，练习把气候路径转化为金融风险假设。"),R("Basel Committee — Climate-related financial risks","https://www.bis.org/committees/bcbs/basel-consolidated-guidelines/module/rma/60","高级","公开资料","银行风险、金融监管与压力测试","阅读最新监管框架，理解治理、风险识别、情景分析和压力测试如何处理气候相关金融风险。") ]},
 "financial-stability":{title:"金融稳定与宏观审慎监管",intro:"从金融周期、杠杆、流动性和传染机制出发，理解系统性风险如何被识别、监测与缓释。",resources:[R("IMF Global Financial Stability Report","https://www.imf.org/en/Publications/GFSR","入门","公开资料","宏观经济学与金融市场基础","用 IMF 半年报告跟踪全球金融脆弱性，并学习把市场现象组织成风险叙事。"),R("FRED Financial Stress Index","https://fred.stlouisfed.org/series/STLFSI4","进阶","公开数据","时间序列、宏观金融与数据可视化","下载并解释金融压力指数，将利率、信用和市场波动与经济事件对齐。"),R("IMF Systemic Macro-Financial Risk Analysis","https://www.imf.org/en/capacity-development/training/icdtc/courses/mfra","高级","课程资料","宏观经济、计量、银行与风险管理","参考 IMF 课程框架研究系统性风险、压力测试、传染、宏观审慎政策及其数据要求。") ]},
 projects:{title:"研究方法与项目",intro:"用明确问题、数据、方法和可复现成果检验理解。",resources:[R("The Turing Way","https://the-turing-way.netlify.app/","入门","开放教材"),R("MIT OpenCourseWare","https://ocw.mit.edu/","进阶","项目资料")]},
 books:{title:"书单与资源",intro:"选择结构完整、练习充分且公开可访问的课程和教材。",resources:[R("OpenStax Economics","https://openstax.org/subjects/business","入门","开放教材"),R("MIT OpenCourseWare Economics","https://ocw.mit.edu/search/?d=Economics","进阶","课程库")]}
};
