import{r,type Phase,type Resource,type SubjectConfig,type Topic}from"./subjectTypes";
type Course=[string,string,string,Resource[],string?];
type Track={slug:string;name:string;en:string;intro:string;caution:string;courses:Course[];tools:SubjectConfig["tools"];books:SubjectConfig["books"];portals:SubjectConfig["portals"]};
const start=["开始之前",[["intro","本站目的"],["how","如何使用本站"],["plan","学习规划"]]] as const;
const coreTimes:Record<string,string[]>={
 electrical:["4–6 个月","3–5 个月","3–5 个月","3–5 个月"],
 mechanical:["4–6 个月","4–6 个月","4–6 个月","3–5 个月"],
 computer:["3–4 个月","4–6 个月","3–5 个月","3–5 个月"],
 aerospace:["4–6 个月","3–5 个月","3–5 个月","5–7 个月"],
 systems:["3–4 个月","4–6 个月","4–6 个月","4–6 个月"],
 materials:["4–6 个月","4–6 个月","3–5 个月","3–5 个月"]
};
const makeTrack=(track:Track):SubjectConfig=>{
 const topics:Record<string,Topic>={tools:{title:"学习工具",intro:`围绕${track.name}建立计算、仿真、设计和实验环境。`,resources:[]},projects:{title:"项目与进阶方向",intro:`以${track.name}的真实约束完成建模、设计、实现、测试和复盘。下面的起点分别对应本学科的核心课程，适合从小型复现逐步发展为综合项目。`,resources:track.courses.map(([, , ,resources])=>resources[0])},books:{title:"书单与资源",intro:"集中查看开放教材与大学官方课程。",resources:[]}};
 track.courses.forEach(([id,title,intro,resources])=>{topics[id]={title,intro,resources}});
 const sections=[...new Set(track.courses.map(course=>course[4]??"核心课程"))];
 const courseGroups=sections.map(section=>[section,track.courses.filter(course=>(course[4]??"核心课程")===section).map(([id,title])=>[id,title] as const)] as const);
 const coreCourses=track.courses.filter(course=>course[4]!=="现代方向");
 const modernCourses=track.courses.filter(course=>course[4]==="现代方向");
 const phases:Phase[]=coreCourses.map(([id,title,intro],index)=>({time:coreTimes[track.slug]?.[index]??(index===0?"3–4 个月":"3–5 个月"),title:`学习${title}`,goal:intro,learn:`完成${title}的主课程、例题和核心习题；从第二阶段开始，每周留出约四分之一时间推进小型项目。`,done:`能独立解释${title}的关键模型，并完成一次计算、仿真或实验。`,link:id,mode:"core"}));
 if(modernCourses.length){
  const choices=modernCourses.map(([,title])=>title).join("、");
  phases.push({time:"按方向 4–6 个月",title:"选择一个现代工程方向",goal:"在共同核心之后分流，不需要把所有前沿方向依次学完。",learn:`从${choices}中选择一条主线，补齐前置要求并完成一套主资源。`,done:"能说明所选方向与工程核心的联系，并完成一个可复现实验、仿真或原型。",link:modernCourses[0][0],mode:"choice"});
 }
 phases.push({time:"从第二阶段持续",title:"完成专业项目",goal:"把分散课程连接为可验证的工程成果。",learn:"需求、模型、设计、测试、数据、文档与安全；后 3–5 个月集中完成综合作品。",done:"发布可复现的项目文件、测试结果和改进记录。",link:"projects",mode:"ongoing"});
 return{slug:`engineering/${track.slug}`,name:track.name,en:track.en,intro:track.intro,caution:track.caution,groups:[start,["起点",[["tools","学习工具"]]],...courseGroups,["实践与资源",[["projects","项目与进阶方向"],["books","书单与资源"]]]],topics,phases,tools:track.tools,books:track.books,portals:track.portals};
};
const commonPortals=(name:string,query:string):SubjectConfig["portals"]=>[["MIT",`MIT OCW ${name}`,`https://ocw.mit.edu/search/?q=${query}`,`检索 ${name} 官方公开课程、讲义与作业。`]];

export const electricalEngineering=makeTrack({slug:"electrical",name:"电子与电气工程",en:"ELECTRICAL ENGINEERING",intro:"电子与电气工程研究电能与信息如何被产生、传输、处理和控制，主线从电路进入信号、器件、电磁、通信与能源系统。",caution:"电气实验必须区分低压原型与高压系统。自学只进行安全低压实验；电网、电机和高功率设备需要专业指导。",courses:[
 ["circuits","电路与电子学","从电压、电流和网络定律进入晶体管、放大器与模拟电路。",[r("All About Circuits Textbook","https://www.allaboutcircuits.com/textbook/","入门","开放教材","代数与基础物理","免费电路教材，适合建立元件和网络直觉。"),r("MIT 6.002 Circuits and Electronics","https://ocw.mit.edu/courses/6-002-circuits-and-electronics-spring-2007/","进阶","公开课","微积分与基础电磁学","系统学习电路、MOS 管、放大器和动态网络。"),r("MIT 6.012 Microelectronic Devices and Circuits","https://ocw.mit.edu/courses/6-012-microelectronic-devices-and-circuits-fall-2009/","高级","公开课","半导体物理与电路","从器件物理连接到微电子电路设计。")]],
 ["signals","信号与系统","学习连续与离散信号、系统响应、傅里叶和采样。",[r("Signals and Systems — LibreTexts","https://eng.libretexts.org/Bookshelves/Electrical_Engineering/Signal_Processing_and_Modeling/Signals_and_Systems_(Baraniuk_et_al.)","入门","开放教材","微积分与复数","用开放教材建立时域和频域语言。"),r("MIT RES.6-007 Signals and Systems","https://ocw.mit.edu/resources/res-6-007-signals-and-systems-spring-2011/","进阶","公开课","微分方程与线性代数","完整视频、讲义和习题覆盖 LTI、变换与滤波。"),r("MIT 6.341 Discrete-Time Signal Processing","https://ocw.mit.edu/courses/6-341-discrete-time-signal-processing-fall-2005/","高级","公开课","信号与系统","深入离散滤波器、频谱和多速率处理。")]],
 ["fields-power","电磁场与能源系统","理解场、波、电机、功率电子和电能转换。",[r("OpenStax University Physics II","https://openstax.org/details/books/university-physics-volume-2","入门","开放教材","微积分与力学","建立静电、磁场、电磁感应和交流电基础。"),r("MIT 6.013 Electromagnetics and Applications","https://ocw.mit.edu/courses/6-013-electromagnetics-and-applications-fall-2005/","进阶","公开课","矢量分析与微分方程","从 Maxwell 方程进入传输线、波与器件。"),r("MIT Power Electronics","https://ocw.mit.edu/search/?q=power%20electronics","高级","公开课","电路、控制与电磁学","研究开关变换器、驱动和能源系统。")]],
 ["communication","通信与数字系统","把信号、概率和硬件连接到可靠的信息传输。",[r("MIT 6.02 Introduction to EECS II","https://ocw.mit.edu/courses/6-02-introduction-to-eecs-ii-digital-communication-systems-fall-2012/","入门","公开课","编程、概率与信号基础","以数字通信网络建立编码和噪声直觉。"),r("MIT 6.450 Principles of Digital Communications I","https://ocw.mit.edu/courses/6-450-principles-of-digital-communications-i-fall-2006/","进阶","公开课","概率与信号系统","系统学习调制、检测、编码与信道。"),r("MIT 6.451 Principles of Digital Communication II","https://ocw.mit.edu/courses/6-451-principles-of-digital-communication-ii-spring-2005/","高级","公开课","数字通信 I","深入编码理论和现代通信系统。")]],
 ["semiconductors-ic","半导体、芯片与光电子","从能带、载流子和器件进入集成电路、纳米电子与光电系统。",[r("MIT 6.701 Introduction to Nanoelectronics","https://ocw.mit.edu/courses/6-701-introduction-to-nanoelectronics-spring-2010/","入门","公开课","电路、线性代数与基础量子物理","从原子尺度建立电流、电压、能带、弹道输运和纳米晶体管模型。"),r("MIT 6.720J Integrated Microelectronic Devices","https://ocw.mit.edu/courses/6-720j-integrated-microelectronic-devices-spring-2007/","进阶","公开课","半导体物理与微电子电路","深入 p-n 结、MOS 结构、短沟道 MOSFET、双极器件和器件缩放。"),r("UC Berkeley EECS 151 Digital Design and Integrated Circuits","https://inst.eecs.berkeley.edu/~eecs151/","高级","公开课","数字逻辑、Verilog 与电路基础","通过 FPGA 或 ASIC 实验学习现代芯片设计、验证、时序、存储器和版图流程。")],"现代方向"],
 ["embedded-iot","嵌入式系统与物联网","把传感器、微控制器、实时软件、无线网络和边缘计算集成为可靠设备。",[r("Embedded Systems — Shape the World","https://users.ece.utexas.edu/~valvano/Volume1/","入门","开放教材","C 与基础电路","德州大学开放教材从 GPIO、中断、ADC 和串行通信进入微控制器实践。"),r("Stanford CS107E Computer Systems from the Ground Up","https://web.stanford.edu/class/cs107e/","进阶","公开课","C、数字逻辑与计算机组成","通过裸机编程学习内存映射 I/O、定时器、传感器、无线通信和系统调试。"),r("Edge Impulse Documentation","https://docs.edgeimpulse.com/","高级","项目平台","嵌入式、信号处理与机器学习基础","完成数据采集、特征设计、TinyML 训练、量化和边缘部署。")],"现代方向"],
 ["power-energy","电力电子、智能电网与新能源","研究高效电能转换、电机驱动、储能并网和电力系统的稳定与控制。",[r("NREL System Advisor Model","https://sam.nrel.gov/","入门","项目平台","电路、能源与基础编程","用美国国家可再生能源实验室开放工具评估光伏、风电和储能系统。"),r("MIT 6.622 Power Electronics","https://ocw.mit.edu/courses/6-622-power-electronics-spring-2023/","进阶","公开课","电路、信号系统与控制","通过现代视频、设计作业和习题学习变换器、磁性元件、调制与控制。"),r("MIT 6.685 Electric Machines","https://ocw.mit.edu/courses/6-685-electric-machines-fall-2013/","高级","公开课","电磁场、电路与动力系统","深入机电能量转换、同步机、感应机、永磁机和电力系统应用。")],"现代方向"]],tools:[["电路与测量",[["LTspice","https://www.analog.com/en/resources/design-tools-and-calculators/ltspice-simulator.html","模拟电路仿真"],["KiCad","https://www.kicad.org/","原理图与 PCB 设计"],["Arduino","https://www.arduino.cc/","安全低压嵌入式实验"]]],["芯片、嵌入式与能源",[["ngspice","https://ngspice.sourceforge.io/","开源混合信号电路仿真"],["PlatformIO","https://platformio.org/","管理嵌入式开发、测试和多平台构建"],["OpenModelica","https://openmodelica.org/","建模电机、电力电子与多物理能源系统"]]]],books:[["All About Circuits","https://www.allaboutcircuits.com/textbook/","电路 · 入门","免费在线电路教材。"],["OpenStax University Physics II","https://openstax.org/details/books/university-physics-volume-2","电磁 · 入门","开放电磁学基础。"],["MIT 6.701 Nanoelectronics","https://ocw.mit.edu/courses/6-701-introduction-to-nanoelectronics-spring-2010/","芯片 · 进阶","带开放教材的纳米电子课程。"],["MIT 6.622 Power Electronics","https://ocw.mit.edu/courses/6-622-power-electronics-spring-2023/","能源 · 进阶","现代电力电子视频、讲义与设计作业。"]],portals:commonPortals("Electrical Engineering","electrical%20engineering")});

export const mechanicalEngineering=makeTrack({slug:"mechanical",name:"机械工程",en:"MECHANICAL ENGINEERING",intro:"机械工程研究力、运动、能量、材料和制造如何共同形成可靠的机器与产品。课程围绕固体力学、热流体、动力学和机械设计展开。",caution:"机械项目涉及旋转件、载荷、热源和加工设备。先做低能量原型，并为结构强度、防护和失效模式保留安全裕度。",courses:[
 ["mechanics","工程力学与固体力学","从受力、运动和材料变形分析机械构件。",[r("OpenStax University Physics I","https://openstax.org/details/books/university-physics-volume-1","入门","开放教材","微积分","复习力学、转动、振动和流体基础。"),r("MIT 2.001 Mechanics & Materials I","https://ocw.mit.edu/courses/2-001-mechanics-materials-i-fall-2006/","进阶","公开课","静力学与微积分","学习载荷、应力、应变和结构响应。"),r("MIT 3.11 Mechanics of Materials","https://ocw.mit.edu/courses/3-11-mechanics-of-materials-fall-1999/","高级","公开课","材料力学","深入梁、扭转、塑性和失效。")]],
 ["thermofluids","热力学与流体力学","研究能量转换、流动、传热和热系统。",[r("OpenStax University Physics II: Thermodynamics","https://openstax.org/books/university-physics-volume-2/pages/1-introduction","入门","开放教材","微积分与基础物理","从温度、热力学定律和输运现象建立基础。"),r("MIT 2.51 Intermediate Heat and Mass Transfer","https://ocw.mit.edu/courses/2-51-intermediate-heat-and-mass-transfer-fall-2008/","进阶","公开课","热力学与微分方程","系统学习热传导、对流、辐射和传质。"),r("MIT 2.25 Advanced Fluid Mechanics","https://ocw.mit.edu/courses/2-25-advanced-fluid-mechanics-fall-2013/","高级","公开课","热力学与流体力学","深入连续介质方程、边界层与粘性流动。")]],
 ["dynamics","动力学、振动与控制","建立机械系统的运动模型并分析稳定性和响应。",[r("MIT 2.003 Modeling Dynamics and Control I","https://ocw.mit.edu/courses/2-003-modeling-dynamics-and-control-i-spring-2005/","入门","公开课","力学与微分方程","从集中参数模型进入机械动力学。"),r("Feedback Systems","https://fbsbook.org/","进阶","开放教材","线性代数与微分方程","学习反馈、稳定性和控制设计。"),r("Underactuated Robotics","https://underactuated.mit.edu/","高级","公开讲义","动力学、控制与优化","深入非线性机械系统和机器人。")]],
 ["design","机械设计与制造","把功能、载荷、材料、公差和制造过程转化为实体产品。",[r("FreeCAD Documentation","https://wiki.freecad.org/Getting_started","入门","公开讲义","无需前置","学习参数化建模并表达机械结构。"),r("MIT 2.007 Design and Manufacturing I","https://ocw.mit.edu/courses/2-007-design-and-manufacturing-i-spring-2009/","进阶","公开课","力学、材料与制图","通过机器人项目完成设计和制造。"),r("MIT 2.008 Design and Manufacturing II","https://ocw.mit.edu/courses/2-008-design-and-manufacturing-ii-spring-2025/","高级","公开课","机械设计与制造基础","进入现代制造工艺、设备控制、质量与面向制造的设计。")]],
 ["mechatronics-robotics","机电一体化与机器人","整合机械结构、传感器、执行器、电子学、实时计算和控制。",[r("Modern Robotics","https://modernrobotics.northwestern.edu/nu-gm-book-resource/","入门","开放教材","线性代数、编程与基础力学","免费教材、视频和代码覆盖运动学、动力学、轨迹生成与机器人控制。"),r("MIT 2.12 Introduction to Robotics","https://ocw.mit.edu/courses/2-12-introduction-to-robotics-fall-2005/","进阶","公开课","动力学、控制与编程","通过传感、运动学、力控制、导航和完整机器人实验连接机械与计算。"),r("MIT 2.737 Mechatronics","https://ocw.mit.edu/courses/2-737-mechatronics-fall-2014/","高级","公开课","电路、控制、嵌入式与机械设计","深入实时接口、传感、功率放大、致动器和机电系统综合设计。")],"现代方向"],
 ["computational-mechanics","计算力学与多物理场仿真","用离散化和高性能计算预测结构、热、流体及其耦合行为。",[r("FEniCSx Tutorials","https://jsdokken.com/dolfinx-tutorial/","入门","公开讲义","Python、微积分与线性代数","从 Poisson 方程逐步学习有限元建模、网格、边界条件和误差检查。"),r("MIT 2.086 Numerical Computation for Mechanical Engineers","https://ocw.mit.edu/courses/2-086-numerical-computation-for-mechanical-engineers-fall-2012/","进阶","公开课","编程、微积分、线性代数与概率","系统学习插值、回归、线性方程、积分、ODE 和工程不确定性。"),r("MIT 16.225 Computational Mechanics of Materials","https://ocw.mit.edu/courses/16-225-computational-mechanics-of-materials-fall-2003/","高级","公开课","连续介质、有限元与成熟编程能力","实现非线性材料、有限变形、动力学、误差估计和并行有限元算法。")],"现代方向"],
 ["digital-manufacturing","数字制造与增材制造","连接参数化设计、制造过程、机器控制、质量数据和快速迭代。",[r("FreeCAD Path Workbench","https://wiki.freecad.org/Path_Workbench","入门","公开讲义","CAD 与基础制造知识","从模型生成刀具路径并理解 CAM、工序、坐标和仿真。"),r("MIT 2.008 Design and Manufacturing II","https://ocw.mit.edu/courses/2-008-design-and-manufacturing-ii-spring-2025/","进阶","公开课","机械设计、材料与制造基础","围绕制造速率、成本、质量、柔性和自动化完成现代制造分析。"),r("MIT How to Make (Almost) Anything","https://fab.cba.mit.edu/classes/863.23/","高级","项目平台","CAD、电子、编程与安全制造实践","综合数字加工、PCB、嵌入式、复合材料、接口和系统集成完成个人作品。")],"现代方向"]],tools:[["机械设计",[["FreeCAD","https://www.freecad.org/","参数化 CAD"],["Onshape Education","https://www.onshape.com/en/education/","浏览器协作 CAD"],["GNU Octave","https://octave.org/","动力学与热流体计算"]]],["机器人与计算工程",[["ROS 2","https://docs.ros.org/","集成机器人软件、传感器和控制器"],["OpenFOAM","https://www.openfoam.com/","开源计算流体力学"],["FEniCSx","https://fenicsproject.org/","有限元和多物理场计算"]]]],books:[["OpenStax University Physics I","https://openstax.org/details/books/university-physics-volume-1","力学 · 入门","开放大学物理教材。"],["OpenStax University Physics II","https://openstax.org/details/books/university-physics-volume-2","热力学 · 入门","开放热学与热力学基础教材。"],["Modern Robotics","https://modernrobotics.northwestern.edu/nu-gm-book-resource/","机器人 · 进阶","免费教材、视频、软件和习题。"],["MIT 2.086 Numerical Computation","https://ocw.mit.edu/courses/2-086-numerical-computation-for-mechanical-engineers-fall-2012/","计算工程 · 进阶","机械工程数值计算课程与编程作业。"]],portals:commonPortals("Mechanical Engineering","mechanical%20engineering")});

export const computerEngineering=makeTrack({slug:"computer",name:"计算机工程",en:"COMPUTER ENGINEERING",intro:"计算机工程位于电子硬件与计算机科学之间，研究数字逻辑、处理器、存储、嵌入式设备和软硬件协同。",caution:"不要把计算机工程等同于一般编程。核心成果应能解释代码如何经过指令集、处理器、存储和接口在真实硬件上运行。",courses:[
 ["digital","数字逻辑与硬件描述","从布尔逻辑、状态机和 HDL 构建数字系统。",[r("Nand2Tetris Part I","https://www.nand2tetris.org/course","入门","项目平台","基础编程","从逻辑门逐步构建 CPU 和计算机。"),r("MIT 6.004 Computation Structures","https://ocw.mit.edu/courses/6-004-computation-structures-spring-2017/","进阶","公开课","编程与基础电路","系统学习数字逻辑、指令与处理器。"),r("MIT 6.111 Introductory Digital Systems Laboratory","https://ocw.mit.edu/courses/6-111-introductory-digital-systems-laboratory-spring-2006/","高级","公开课","数字逻辑与 HDL","通过 FPGA 完成复杂数字系统。")]],
 ["architecture","计算机组成与体系结构","理解指令集、流水线、缓存、虚拟内存与并行。",[r("Berkeley CS61C","https://cs61c.org/","入门","公开课","C 与数据结构","从 C、汇编和 RISC-V 进入机器结构。"),r("MIT 6.823 Computer System Architecture","https://ocw.mit.edu/courses/6-823-computer-system-architecture-fall-2005/","进阶","公开课","数字逻辑与组成原理","系统学习流水线、存储层次和多处理器。"),r("Berkeley CS152","https://inst.eecs.berkeley.edu/~cs152/","高级","公开课","体系结构基础","通过处理器设计深入现代体系结构。")]],
 ["embedded","嵌入式与实时系统","连接微控制器、传感器、接口、操作系统和实时约束。",[r("Embedded Systems — Shape the World","https://users.ece.utexas.edu/~valvano/Volume1/","入门","开放教材","C 与基础电路","从微控制器 I/O 和中断开始实践。"),r("MIT 6.S081 Operating System Engineering","https://pdos.csail.mit.edu/6.S081/2021/","进阶","公开课","C、体系结构与调试","通过 xv6 理解硬件与操作系统接口。"),r("MIT 6.182 Mobile and Sensor Computing","https://catalog.mit.edu/subjects/6/","高级","公开课","嵌入式、网络与概率","进入传感、移动和受限计算系统。")]],
 ["hardware-systems","硬件系统与协同设计","综合处理器、接口、软件、验证与性能工程。",[r("RISC-V Specifications","https://riscv.org/specifications/","入门","公开讲义","组成原理","阅读开放指令集规范并实现小型实验。"),r("OpenROAD Project","https://theopenroadproject.org/","进阶","项目平台","HDL 与数字电路","了解开放芯片设计流程。"),r("MIT 6.2050 Digital Systems Laboratory","https://catalog.mit.edu/subjects/6/","高级","公开课","数字系统与计算机组成","围绕 FPGA、接口和验证完成系统项目。")]],
 ["chip-design","数字芯片设计与验证","从 RTL、FPGA 和 CMOS 时序进入 ASIC 综合、物理设计与形式验证。",[r("UC Berkeley EECS 151 Digital Design and Integrated Circuits","https://inst.eecs.berkeley.edu/~eecs151/","入门","公开课","数字逻辑与基础 Verilog","公开讲义、讨论和实验覆盖 SystemVerilog、FPGA、ASIC、时序、存储器与验证。"),r("MIT 6.884 Complex Digital Systems","https://ocw.mit.edu/courses/6-884-complex-digital-systems-spring-2005/","进阶","公开课","HDL、体系结构与数字电路","以大型 CMOS VLSI 项目学习模块化设计、高层综合、面积功耗时序权衡和验证。"),r("OpenROAD Project","https://theopenroadproject.org/","高级","项目平台","RTL、Linux、脚本与芯片设计基础","使用开放 EDA 流程把 RTL 推进到布局布线，并记录 PPA 与设计规则结果。")],"现代方向"],
 ["edge-ai","AI 加速器、TinyML 与边缘计算","研究如何让机器学习在功耗、内存和时延受限的硬件上高效运行。",[r("Machine Learning Systems","https://www.mlsysbook.ai/","入门","开放教材","计算机组成、Python 与机器学习基础","开放教材连接数据、训练、推理、硬件、部署和可靠性。"),r("MIT EfficientML.ai Course","https://hanlab.mit.edu/courses/2024-fall-65940","进阶","公开课","深度学习、体系结构与 PyTorch","学习剪枝、量化、神经架构搜索、编译优化、分布式训练和边缘部署。"),r("MLPerf Tiny","https://mlcommons.org/working-groups/benchmarks/tiny/","高级","项目平台","嵌入式、模型优化与性能测量","在标准任务上测量延迟、能耗和精度，比较微控制器端推理方案。")],"现代方向"],
 ["hardware-security","硬件安全与可信计算","理解侧信道、瞬态执行、故障注入、可信启动和安全处理器设计。",[r("ChipWhisperer Learning Platform","https://learn.chipwhisperer.io/","入门","项目平台","数字逻辑、嵌入式与基础密码学","用安全实验平台学习功耗分析、时序侧信道和故障注入。"),r("MIT 6.5950 Secure Hardware Design","https://ocw.mit.edu/courses/6-5950-secure-hardware-design-spring-2025/","进阶","公开课","计算机体系结构、C/C++ 与操作系统","通过攻击真实处理器学习缓存侧信道、Spectre、内存安全和体系结构防御。"),r("OpenTitan Documentation","https://opentitan.org/book/","高级","项目平台","RTL、SoC、密码学与验证","阅读开源硅信任根的安全架构，并研究安全启动、密钥管理和硬件生命周期。")],"现代方向"]],tools:[["硬件开发",[["Logisim Evolution","https://github.com/logisim-evolution/logisim-evolution","数字电路仿真"],["RISC-V","https://riscv.org/","开放指令集资料"],["PlatformIO","https://platformio.org/","嵌入式开发环境"]]],["芯片与性能",[["Verilator","https://www.veripool.org/verilator/","高速 RTL 仿真与检查"],["Yosys","https://yosyshq.net/yosys/","开源 Verilog 综合"],["OpenROAD","https://theopenroadproject.org/","开放 ASIC 物理设计流程"]]]],books:[["Nand2Tetris","https://www.nand2tetris.org/","数字系统 · 入门","免费课程与项目。"],["RISC-V Specifications","https://riscv.org/specifications/","体系结构 · 进阶","开放指令集规范。"],["Machine Learning Systems","https://www.mlsysbook.ai/","AI 系统 · 进阶","免费连接模型、硬件、优化与部署。"],["OpenTitan Documentation","https://opentitan.org/book/","可信硬件 · 高级","开源硅信任根架构与实现文档。"]],portals:[["UIUC","UIUC Computer Engineering BS","https://catalog.illinois.edu/undergraduate/engineering/computer-engineering-bs/","计算机工程核心课程与专业方向。"],["Berkeley","UC Berkeley EECS 151","https://inst.eecs.berkeley.edu/~eecs151/","公开数字芯片设计讲义、作业与 FPGA/ASIC 实验。"],...commonPortals("Computer Engineering","computer%20engineering")]});

export const aerospaceEngineering=makeTrack({slug:"aerospace",name:"航空航天工程",en:"AEROSPACE ENGINEERING",intro:"航空航天工程围绕飞机、火箭、卫星和自主飞行器，整合空气动力学、推进、结构、飞行动力学与系统设计。",caution:"飞行器设计对安全、法规和验证要求极高。自学应以仿真、公开数据和低风险模型为主，不开展未经指导的推进、高压或载人实验。",courses:[
 ["aerodynamics","空气动力学与流体","研究翼型、边界层、可压缩流和飞行性能。",[r("NASA Beginner’s Guide to Aeronautics","https://www.nasa.gov/stem-content/beginners-guide-to-aeronautics/","入门","公开讲义","代数与基础物理","建立升力、阻力和飞行的直觉。"),r("MIT 16.100 Aerodynamics","https://ocw.mit.edu/courses/16-100-aerodynamics-fall-2005/","进阶","公开课","流体力学与微分方程","系统学习势流、翼型和有限翼。"),r("MIT Compressible Flow","https://ocw.mit.edu/search/?q=compressible%20flow","高级","公开课","热力学与流体力学","进入激波、喷管和高速空气动力学。")]],
 ["structures","航空航天结构","分析轻质结构、材料、载荷、振动和结构失效。",[r("MIT 16.01 Unified Engineering: Materials and Structures","https://ocw.mit.edu/courses/16-01-unified-engineering-i-ii-iii-iv-fall-2005-spring-2006/","入门","公开课","力学与微积分","在飞行器背景中学习材料与结构。"),r("MIT Aerospace Structures","https://ocw.mit.edu/search/?q=aerospace%20structures","进阶","公开课","材料力学","研究薄壁结构、屈曲和轻量化。"),r("NASA Technical Reports Server","https://ntrs.nasa.gov/","高级","项目平台","结构、统计与文献阅读","使用真实技术报告研究结构验证与失效。")]],
 ["propulsion","航空与航天推进","连接热力学、流体、燃烧、喷气发动机和火箭。",[r("NASA Beginner’s Guide to Propulsion","https://www.grc.nasa.gov/www/k-12/airplane/bgp.html","入门","公开讲义","基础热学与流体","理解喷气和火箭推进的主要部件。"),r("MIT 16.50 Introduction to Propulsion Systems","https://ocw.mit.edu/courses/16-50-introduction-to-propulsion-systems-spring-2012/","进阶","公开课","热力学与流体力学","覆盖热机、喷气和火箭推进。"),r("MIT Rocket Propulsion","https://ocw.mit.edu/search/?q=rocket%20propulsion","高级","公开课","可压缩流与燃烧","深入火箭发动机性能与设计。")]],
 ["flight-space","飞行动力学、控制与航天系统","研究稳定性、制导控制、轨道和任务设计。",[r("MIT 16.00 Introduction to Aerospace Engineering and Design","https://ocw.mit.edu/courses/16-00-introduction-to-aerospace-engineering-and-design-spring-2003/","入门","公开课","力学与微积分","通过综合设计认识航空与航天系统。"),r("MIT 16.07 Dynamics","https://ocw.mit.edu/courses/16-07-dynamics-fall-2009/","进阶","公开课","经典力学与微分方程","学习飞行器动力学所需的运动学和动力学。"),r("MIT 16.346 Astrodynamics","https://ocw.mit.edu/courses/16-346-astrodynamics-fall-2008/","高级","公开课","动力学、控制与数值方法","进入轨道、摄动和航天任务分析。")]],
 ["spacecraft","卫星与深空系统","把轨道、结构、热控、电源、通信、姿态控制和任务运营整合为航天器。",[r("NASA Systems Engineering Handbook","https://www.nasa.gov/reference/systems-engineering-handbook/","入门","开放教材","基础工程设计","用 NASA 标准框架学习需求、接口、技术风险、验证与系统生命周期。"),r("MIT 16.851 Satellite Engineering","https://ocw.mit.edu/courses/16-851-satellite-engineering-fall-2003/","进阶","公开课","轨道力学、电路、热学与控制","通过讲义和设计作业权衡卫星电源、结构、通信、热控、姿态和地面系统。"),r("MIT 16.842 Fundamentals of Systems Engineering","https://ocw.mit.edu/courses/16-842-fundamentals-of-systems-engineering-fall-2015/","高级","公开课","工程设计与项目经验","围绕复杂航空航天系统学习架构、风险、接口、验证、制造和运营。")],"现代方向"],
 ["autonomous-flight","自主飞行与无人系统","融合感知、定位、规划、制导控制和安全验证，构建无人机与自主航天器。",[r("PX4 User Guide","https://docs.px4.io/main/en/","入门","项目平台","Linux、C++ 或 Python 与基础控制","在仿真中配置飞控、传感器、任务和安全机制，不进行高风险实飞。"),r("MIT 16.410 Principles of Autonomy and Decision Making","https://ocw.mit.edu/courses/16-410-principles-of-autonomy-and-decision-making-fall-2010/","进阶","公开课","算法、概率、优化与控制","学习搜索、规划、执行、MDP 和自主系统决策。"),r("MIT 16.S498 Risk Aware and Robust Nonlinear Planning","https://ocw.mit.edu/courses/16-s498-risk-aware-and-robust-nonlinear-planning-fall-2019/","高级","公开课","非线性系统、概率与凸优化","研究不确定环境中的风险约束规划、鲁棒控制和安全验证。")],"现代方向"],
 ["computational-aerospace","计算航空航天与数字工程","用 CFD、结构计算、优化和多学科设计探索飞行器并验证数字模型。",[r("NASA OpenVSP Ground School","https://vspu.larc.nasa.gov/","入门","公开课","空气动力学与基础 CAD","使用 NASA 开源工具建立飞机几何并进行参数、质量和气动分析。"),r("MIT 6.336J Introduction to Numerical Simulation","https://ocw.mit.edu/courses/6-336j-introduction-to-numerical-simulation-sma-5211-fall-2003/","进阶","公开课","编程、线性代数与微分方程","学习线性系统、插值、数值积分、ODE/PDE 和工程误差分析。"),r("SU2 Tutorials","https://su2code.github.io/tutorials/home/","高级","项目平台","流体力学、数值方法与 Linux","复现外流、可压缩流、伴随优化和多物理耦合案例。")],"现代方向"]],tools:[["航空航天计算",[["OpenVSP","https://openvsp.org/","NASA 开源飞行器几何工具"],["SU2","https://su2code.github.io/","开源 CFD 与设计"],["GMAT","https://gmat.atlassian.net/wiki/spaces/GW/overview","开源航天任务分析"]]],["任务与自主系统",[["NASA OpenMDAO","https://openmdao.org/","多学科设计分析与优化"],["PX4","https://px4.io/","开源无人机飞控与软件在环仿真"],["Basilisk","https://avslab.github.io/basilisk/","航天器动力学、制导导航与控制仿真"]]]],books:[["NASA Beginner’s Guide","https://www.nasa.gov/stem-content/beginners-guide-to-aeronautics/","航空 · 入门","NASA 飞行与推进资料。"],["MIT Unified Engineering","https://ocw.mit.edu/courses/16-01-unified-engineering-i-ii-iii-iv-fall-2005-spring-2006/","综合 · 进阶","MIT 航空航天核心课程。"],["NASA Systems Engineering Handbook","https://www.nasa.gov/reference/systems-engineering-handbook/","航天系统 · 进阶","复杂系统全生命周期的权威开放手册。"],["MIT Satellite Engineering","https://ocw.mit.edu/courses/16-851-satellite-engineering-fall-2003/","卫星 · 高级","卫星子系统讲义、设计作业与项目。"]],portals:[["MIT","MIT AeroAstro Curriculum","https://catalog.mit.edu/schools/engineering/aeronautics-astronautics/","航空航天本科核心与专业方向。"],["NASA","NASA Technical Reports Server","https://ntrs.nasa.gov/","检索飞行器、推进、空间系统和任务验证技术报告。"],...commonPortals("Aerospace Engineering","aerospace%20engineering")]});

export const controlEngineering=makeTrack({slug:"systems",name:"控制与系统工程",en:"CONTROL AND SYSTEMS ENGINEERING",intro:"控制与系统工程研究动态系统如何被建模、估计、反馈和优化，服务于机器人、飞行器、能源和复杂工程系统。",caution:"控制器在仿真中稳定，不代表真实系统安全。必须考虑传感误差、执行器限制、时延、饱和与失效保护。",courses:[
 ["modeling","动态系统建模","用微分方程、状态空间和数据描述系统动态。",[r("MIT 6.01SC Signals and Systems","https://ocw.mit.edu/courses/6-01sc-introduction-to-electrical-engineering-and-computer-science-i-spring-2011/pages/unit-2-signals-and-systems/","入门","公开课","微积分与编程","从状态机和系统响应建立模型直觉。"),r("MIT RES.6-007 Signals and Systems","https://ocw.mit.edu/resources/res-6-007-signals-and-systems-spring-2011/","进阶","公开课","微分方程与线性代数","学习系统、变换与频率响应。"),r("MIT System Identification","https://ocw.mit.edu/search/?q=system%20identification","高级","公开课","概率、优化与动态系统","从实验数据估计模型和不确定性。")]],
 ["feedback","反馈控制","学习稳定性、PID、频域方法、状态反馈和鲁棒性。",[r("Feedback Systems","https://fbsbook.org/","入门","开放教材","微积分与线性代数","开放教材连接反馈直觉和数学。"),r("MIT 6.302 Feedback Systems","https://ocw.mit.edu/courses/6-302-feedback-systems-spring-2007/","进阶","公开课","信号系统与微分方程","系统学习频率设计和反馈实现。"),r("MIT 16.30 Feedback Control Systems","https://catalog.mit.edu/subjects/16/","高级","公开课","状态空间与概率","进入多变量控制、估计和鲁棒性。")]],
 ["estimation","状态估计与最优控制","在噪声和约束下进行估计、规划与决策。",[r("Kalman Filter — Welch & Bishop","https://www.mit.edu/course/16/16.070/www/project/PF_kalman_intro.pdf","入门","公开讲义","概率与线性代数","MIT 保存的经典入门讲义，简明建立卡尔曼滤波概念。"),r("Stanford EE363 Linear Dynamical Systems","https://web.stanford.edu/class/ee363/","进阶","公开课","状态空间与优化","学习估计、LQR 和线性动态系统。"),r("MIT Dynamic Systems and Control","https://catalog.mit.edu/subjects/6/","高级","公开课","控制、概率与优化","深入多变量、最优与鲁棒控制。")]],
 ["robotics","机器人与系统集成","把感知、规划、控制、接口和安全连接为完整系统。",[r("Modern Robotics","https://modernrobotics.northwestern.edu/nu-gm-book-resource/","入门","开放教材","线性代数与编程","免费教材和视频覆盖运动学与控制。"),r("MIT Underactuated Robotics","https://underactuated.mit.edu/","进阶","公开讲义","动力学、控制与优化","研究非线性机器人和运动规划。"),r("MIT Robotics: Science and Systems","https://ocw.mit.edu/search/?q=robotics%20science%20systems","高级","公开课","机器人基础与概率","综合定位、规划、感知和系统实现。")]],
 ["nonlinear-robust","非线性与鲁棒控制","在非线性、参数误差和外部扰动下分析稳定性并设计可靠控制器。",[r("MIT 16.30 Feedback Control Systems","https://ocw.mit.edu/courses/16-30-feedback-control-systems-fall-2010/","入门","公开课","线性控制、状态空间与 MATLAB","从线性化和 Lyapunov 思想到模型不确定性、鲁棒性与非线性控制概览。"),r("MIT 6.243J Dynamics of Nonlinear Systems","https://ocw.mit.edu/courses/6-243j-dynamics-of-nonlinear-systems-fall-2003/","进阶","公开课","微分方程、线性代数与反馈控制","学习非线性行为、Lyapunov 稳定性、反馈线性化和绝对稳定性。"),r("MIT Underactuated Robotics","https://underactuated.mit.edu/","高级","公开讲义","非线性动力学、优化与控制","用轨迹优化、控制 Lyapunov 函数和随机系统研究欠驱动机器人。")],"现代方向"],
 ["optimal-mpc","最优控制与模型预测控制","在动力学和约束下优化轨迹，并以滚动时域方法实时重新规划。",[r("Stanford EE364A Convex Optimization","https://web.stanford.edu/class/ee364a/","入门","公开课","线性代数、多变量微积分与概率","建立凸建模、对偶和数值优化基础，为 MPC 求解器做准备。"),r("MIT 16.323 Principles of Optimal Control","https://ocw.mit.edu/courses/16-323-principles-of-optimal-control-spring-2008/","进阶","公开课","状态空间、微分方程与优化","学习变分法、动态规划、LQR、轨迹优化和模型预测控制。"),r("do-mpc Documentation","https://www.do-mpc.com/","高级","项目平台","控制、优化与 Python","在非线性系统、约束和不确定性下实现 MPC、估计与闭环仿真。")],"现代方向"],
 ["learning-control","学习控制与自主决策","结合系统辨识、强化学习和安全约束，让控制器从数据中改进。",[r("Stanford AA203 Optimal and Learning-based Control","https://stanfordasl.github.io/aa203/","入门","公开课","控制、概率、优化与 Python","连接最优控制、Hamilton–Jacobi 可达性、MPC、模型学习和强化学习。"),r("UC Berkeley CS285 Deep Reinforcement Learning","https://rail.eecs.berkeley.edu/deeprlcourse/","进阶","公开课","机器学习、概率与深度学习","从策略梯度、价值学习进入模型式强化学习、离线学习和控制应用。"),r("MIT 16.S498 Risk Aware and Robust Nonlinear Planning","https://ocw.mit.edu/courses/16-s498-risk-aware-and-robust-nonlinear-planning-fall-2019/","高级","公开课","非线性系统、概率与凸优化","用矩和半定规划研究不确定系统的风险约束控制与安全验证。")],"现代方向"]],tools:[["建模与控制",[["Python Control Systems Library","https://python-control.readthedocs.io/","控制分析与设计"],["GNU Octave","https://octave.org/","矩阵与动态系统计算"],["ROS","https://www.ros.org/","机器人系统集成"]]],["优化与自主系统",[["CasADi","https://web.casadi.org/","自动微分、最优控制与轨迹优化"],["do-mpc","https://www.do-mpc.com/","非线性模型预测控制与估计"],["MuJoCo","https://mujoco.org/","机器人动力学、接触和学习控制仿真"]]]],books:[["Feedback Systems","https://fbsbook.org/","控制 · 入门","公开反馈控制教材。"],["Modern Robotics","https://modernrobotics.northwestern.edu/nu-gm-book-resource/","机器人 · 进阶","免费教材、视频和代码。"],["Underactuated Robotics","https://underactuated.mit.edu/","非线性控制 · 进阶","持续更新的 MIT 开放讲义与练习。"],["Stanford AA203","https://stanfordasl.github.io/aa203/","学习控制 · 高级","最优控制、可达性和学习控制资料。"]],portals:[["Stanford","Stanford Autonomous Systems Lab Courses","https://stanfordasl.github.io/","自主系统、最优控制、规划与安全研究课程。"],...commonPortals("Control Systems","control%20systems")]});

export const materialsEngineering=makeTrack({slug:"materials",name:"材料工程",en:"MATERIALS SCIENCE AND ENGINEERING",intro:"材料工程以加工—结构—性能—应用为主线，研究金属、陶瓷、聚合物、半导体和复合材料如何被设计与验证。",caution:"材料实验可能涉及高温、压力、化学品和制样设备。自学以数据、仿真和公开案例为主，实验必须遵守专业安全规范。",courses:[
 ["structure","材料结构与热力学","从原子键、晶体和缺陷进入相平衡与材料稳定性。",[r("MIT 3.091 Introduction to Solid-State Chemistry","https://ocw.mit.edu/courses/3-091-introduction-to-solid-state-chemistry-fall-2018/","入门","公开课","普通化学与基础物理","建立固体结构和材料性质基础。"),r("MIT 3.020 Thermodynamics of Materials","https://ocw.mit.edu/courses/3-020-thermodynamics-of-materials-spring-2021/","进阶","公开课","热力学与微积分","学习相平衡、化学势和材料稳定性。"),r("MIT Phase Transformations","https://ocw.mit.edu/search/?q=phase%20transformations%20materials","高级","公开课","材料热力学与动力学","深入形核、长大和微结构演化。")]],
 ["properties","材料力学与功能性质","理解微观结构如何决定力、电、磁、光和热性质。",[r("OpenStax University Physics","https://openstax.org/details/books/university-physics-volume-1","入门","开放教材","微积分","补充力学、电磁和热学基础。"),r("MIT 3.11 Mechanics of Materials","https://ocw.mit.edu/courses/3-11-mechanics-of-materials-fall-1999/","进阶","公开课","静力学与材料结构","学习弹塑性、断裂和结构响应。"),r("MIT Electronic, Optical and Magnetic Properties","https://ocw.mit.edu/search/?q=electronic%20optical%20magnetic%20properties%20materials","高级","公开课","量子与固体基础","连接电子结构与功能材料。")]],
 ["processing","材料加工与微结构","研究凝固、热处理、成形、烧结和聚合物加工。",[r("DoITPoMS Teaching Resources","https://www.doitpoms.ac.uk/","入门","公开讲义","材料结构基础","剑桥材料教学模块和交互内容。"),r("MIT 3.044 Materials Processing","https://ocw.mit.edu/courses/3-044-materials-processing-spring-2013/","进阶","公开课","热力学、流体与传热","用输运过程理解材料加工。"),r("MIT Microstructural Evolution","https://ocw.mit.edu/search/?q=microstructural%20evolution","高级","公开课","扩散与相变","研究加工路径如何塑造微结构。")]],
 ["characterization","材料表征、选材与设计","用实验和计算识别结构、性质与失效，并针对工况选材。",[r("Materials Project","https://materialsproject.org/","入门","项目平台","材料基础与数据分析","探索开放材料结构和计算性质。"),r("MIT Materials Laboratory","https://ocw.mit.edu/search/?q=materials%20laboratory","进阶","公开课","材料结构与统计","学习表征、实验设计和数据解释。"),r("NIST Materials Data Repository","https://materialsdata.nist.gov/","高级","项目平台","材料学、统计与编程","使用权威数据完成材料比较或失效研究。")]],
 ["computational-materials","计算材料与材料信息学","用量子计算、分子动力学和数据方法预测材料结构、性质与合成候选。",[r("Materials Project Workshops","https://workshop.materialsproject.org/","入门","项目平台","材料基础、Python 与数据分析","学习检索开放材料数据、使用 API 并完成结构与性质分析。"),r("MIT 3.320 Atomistic Computer Modeling of Materials","https://ocw.mit.edu/courses/3-320-atomistic-computer-modeling-of-materials-sma-5107-spring-2005/","进阶","公开课","热统计、量子力学与编程","实践势函数、密度泛函、分子动力学、Monte Carlo 和多尺度建模。"),r("Materials Cloud LEARN","https://www.materialscloud.org/learn","高级","项目平台","计算材料、Linux 与电子结构基础","使用开放教程和可复现工作流开展量子材料计算与数据共享。")],"现代方向"],
 ["nano-quantum","纳米、电子与量子材料","研究尺寸效应、量子输运、光电磁性质以及低维和拓扑材料。",[r("MIT 6.701 Introduction to Nanoelectronics","https://ocw.mit.edu/courses/6-701-introduction-to-nanoelectronics-spring-2010/","入门","公开课","电磁学与基础量子力学","从原子尺度学习能带、分子与纳米管、弹道输运和器件极限。"),r("MIT 3.024 Electronic, Optical and Magnetic Properties of Materials","https://ocw.mit.edu/courses/3-024-electronic-optical-and-magnetic-properties-of-materials-spring-2013/","进阶","公开课","材料基础、量子与热统计","连接电子结构与光纤、磁存储、太阳能电池、晶体管等功能器件。"),r("MIT 3.052 Nanomechanics of Materials and Biomaterials","https://ocw.mit.edu/courses/3-052-nanomechanics-of-materials-and-biomaterials-spring-2007/","高级","公开课","材料力学、统计物理与生物基础","研究纳米尺度的表面力、黏附、单分子力学和生物材料。")],"现代方向"],
 ["energy-sustainable","能源材料与可持续设计","围绕电池、燃料电池、光伏和循环利用权衡性能、寿命、资源与环境影响。",[r("NREL Materials Synthesis and Characterization","https://www.nrel.gov/materials-science/materials-synthesis-characterization.html","入门","项目平台","材料与能源基础","通过国家实验室公开研究入口了解光伏、储能、氢能和材料可靠性问题。"),r("MIT 10.626 Electrochemical Energy Systems","https://ocw.mit.edu/courses/10-626-electrochemical-energy-systems-spring-2014/","进阶","公开课","热力学、传输现象与电化学","学习电池、燃料电池、超级电容的反应、输运、多孔电极与相变模型。"),r("MIT 2.60J Fundamentals of Advanced Energy Conversion","https://ocw.mit.edu/courses/2-60j-fundamentals-of-advanced-energy-conversion-spring-2020/","高级","公开课","热统计、量子、传热与材料基础","从基本物理分析太阳能、热电、燃料电池、储能和能源转换材料。")],"现代方向"]],tools:[["材料数据与建模",[["Materials Project","https://materialsproject.org/","开放计算材料数据库"],["VESTA","https://jp-minerals.org/vesta/en/","晶体结构可视化"],["ImageJ","https://imagej.net/","显微图像分析"]]],["原子模拟与信息学",[["pymatgen","https://pymatgen.org/","材料结构、相图和计算数据分析"],["ASE","https://ase-lib.org/","建立和自动化原子尺度模拟"],["LAMMPS","https://www.lammps.org/","经典分子动力学与材料模拟"]]]],books:[["DoITPoMS","https://www.doitpoms.ac.uk/","材料 · 入门","剑桥大学开放教学模块。"],["MIT 3.091","https://ocw.mit.edu/courses/3-091-introduction-to-solid-state-chemistry-fall-2018/","固体 · 入门","完整公开课程。"],["MIT 3.320 Atomistic Modeling","https://ocw.mit.edu/courses/3-320-atomistic-computer-modeling-of-materials-sma-5107-spring-2005/","计算材料 · 进阶","讲义、视频、习题与模拟实验。"],["Materials Cloud LEARN","https://www.materialscloud.org/learn","材料信息学 · 进阶","可复现的计算材料教程与开放工作流。"]],portals:[["MIT","MIT Materials Curriculum","https://catalog.mit.edu/degree-charts/materials-science-engineering-course-3/","材料工程本科课程结构。"],["Materials Project","Materials Project Community Resources","https://docs.materialsproject.org/community/community-resources","开放数据库、工作坊和材料信息学教程。"],...commonPortals("Materials Science","materials%20science")]});

export const engineeringTracks=[electricalEngineering,mechanicalEngineering,computerEngineering,aerospaceEngineering,controlEngineering,materialsEngineering];
