import {r,type SubjectConfig,type Topic} from "./subjectTypes";
const t=(title:string,intro:string,resources:ReturnType<typeof r>[]):Topic=>({title,intro,resources});
const start=["开始之前",[["plan","学习规划"]]] as const;
const socialTopics:Record<string,Topic>={
 tools:t("学习工具","检索数据、文献和政策材料，保存透明的分析过程。",[]),
 methods:t("研究方法与统计","学习调查、实验、访谈、比较研究、因果推断和研究伦理。",[r("Social Science Research: Principles, Methods, and Practices","https://digitalcommons.usf.edu/oa_textbooks/3/","入门","开放教材","无需前置","免费介绍理论、测量、抽样和定量定性方法。"),r("OpenIntro Statistics","https://www.openintro.org/book/os/","进阶","开放教材","高中代数","用开放教材建立统计推断基础。"),r("Causal Inference: The Mixtape","https://mixtape.scunning.com/","高级","开放教材","回归、概率与编程","免费学习实验、匹配、断点和双重差分。")]),
 sociology:t("社会学","研究制度、阶层、文化、组织与日常互动。",[r("OpenStax Introduction to Sociology 3e","https://openstax.org/details/books/introduction-sociology-3e","入门","开放教材","无需前置","系统覆盖社会结构与主要理论。"),r("MIT Sociology","https://ocw.mit.edu/search/?q=sociology","进阶","公开课","社会学导论","用大学课程深化不平等、组织和社会变迁。"),r("UC Berkeley Sociology Courses","https://sociology.berkeley.edu/undergraduate-courses-1","高级","公开讲义","理论、方法与统计","按专题进入理论、人口、文化和分层研究。")]),
 politics:t("政治学与公共政策","理解权力、国家、制度、集体行动和政策选择。",[r("OpenStax Introduction to Political Science","https://openstax.org/details/books/introduction-political-science","入门","开放教材","无需前置","免费建立比较政治、国际关系和政治行为框架。"),r("MIT Introduction to Political Science","https://ocw.mit.edu/search/?q=introduction%20political%20science","进阶","公开课","政治学导论与历史常识","从制度、战略互动和证据理解政治。"),r("MIT Public Policy","https://ocw.mit.edu/search/?q=public%20policy","高级","公开课","经济学、统计与政治学","学习政策分析、评估和实施。")]),
 anthropology:t("人类学","通过跨文化比较理解社会、意义、亲属、交换和权力。",[r("OpenStax Introduction to Anthropology","https://openstax.org/details/books/introduction-anthropology","入门","开放教材","无需前置","覆盖生物、考古、语言和文化人类学。"),r("MIT 21A.00 Introduction to Anthropology","https://ocw.mit.edu/courses/21a-00-introduction-to-anthropology-spring-2013/","进阶","公开课","无需前置","以民族志案例讨论文化、身份、经济和政治。"),r("MIT Anthropology Courses","https://ocw.mit.edu/search/?d=Anthropology","高级","公开课","人类学导论与社会理论","按医疗、技术、全球化等专题继续研究。")]),
 economics:t("经济学与制度","研究稀缺、激励、市场、组织、增长和分配。",[r("CORE Econ: The Economy 2.0","https://www.core-econ.org/the-economy/","入门","开放教材","高中代数","以现实问题、数据和制度引入经济学。"),r("MIT Principles of Economics","https://ocw.mit.edu/search/?q=principles%20economics","进阶","公开课","代数与基础统计","系统学习微观、宏观和实证分析。"),r("MIT Political Economy","https://ocw.mit.edu/search/?q=political%20economy","高级","公开课","微观经济学、博弈论与政治学","研究制度与政治如何塑造经济结果。")]),
 population:t("人口、城市与全球发展","用人口、空间和发展数据理解迁移、城市化与不平等。",[r("Our World in Data","https://ourworldindata.org/","入门","项目平台","基础图表阅读","从可追溯数据探索全球社会问题。"),r("World Bank Open Data","https://data.worldbank.org/","进阶","项目平台","统计与表格工具","比较国家发展、教育、健康和人口指标。"),r("IPUMS","https://www.ipums.org/","高级","项目平台","统计、数据清洗与研究伦理","使用标准化微观数据开展人口和社会研究。")]),
 theory:t("社会理论与跨学科议题","比较解释秩序、冲突、现代性、身份和技术的理论。",[r("Introduction to Social Theory","https://oyc.yale.edu/sociology/socy-151","入门","公开课","社会学导论","Yale 公开课梳理经典社会理论。"),r("MIT Social Theory","https://ocw.mit.edu/search/?q=social%20theory","进阶","公开课","社会学、政治学与历史","把概念放回原始文本和历史语境。"),r("Stanford Encyclopedia of Philosophy","https://plato.stanford.edu/","高级","开放教材","理论阅读经验","检索概念谱系和权威参考文献。")]),
 projects:t("项目与进阶方向","围绕真实社会问题完成数据、比较或田野型研究。",[r("Our World in Data Grapher","https://ourworldindata.org/grapher","入门","项目平台","基础统计","选择一个指标复现图表并检查来源。"),r("Harvard Dataverse","https://dataverse.harvard.edu/","进阶","项目平台","统计、研究设计与编程","寻找公开数据并复现一项社会科学分析。"),r("ICPSR","https://www.icpsr.umich.edu/","高级","项目平台","定量方法与研究伦理","使用社会调查数据提出可检验问题。")]),
 books:t("书单与资源","集中查看开放教材和大学课程。",[])
};
export const socialScience:SubjectConfig={slug:"social-science",name:"社会科学",en:"SOCIAL SCIENCE",intro:"社会科学用理论、历史比较、调查、实验和数据理解个人、制度与社会结构如何相互塑造。",caution:"研究社会问题时，价值判断和事实判断都重要但不能混为一谈。明确概念、证据、因果假设、代表性与伦理边界。",groups:[start,["基础",[["tools","学习工具"],["methods","研究方法与统计"]]],["学科核心",[["sociology","社会学"],["politics","政治学与公共政策"],["anthropology","人类学"],["economics","经济学与制度"]]],["综合与实践",[["population","人口、城市与全球发展"],["theory","社会理论与跨学科议题"],["projects","项目与进阶方向"],["books","书单与资源"]]]],topics:socialTopics,phases:[{time:"1–2 个月",title:"建立研究方法意识",goal:"把宏大议题转成可研究的问题。",learn:"概念、测量、抽样、比较、相关、因果和伦理。",done:"能拆解一项研究的论点、证据与限制。",link:"methods"},{time:"3–5 个月",title:"建立四个学科视角",goal:"从制度、文化、权力和激励解释社会。",learn:"社会学、政治学、人类学与经济学导论。",done:"用至少两种视角解释同一现象。",link:"sociology"},{time:"2–4 个月",title:"学会阅读社会数据",goal:"避免只凭个案和印象判断。",learn:"描述统计、可视化、调查和公开数据。",done:"完成一个有数据来源和限制说明的分析。",link:"population"},{time:"2–4 个月",title:"进入理论与专题",goal:"连接经典理论和当代问题。",learn:"阶层、国家、城市、技术、性别、全球化。",done:"写一篇比较理论与证据的短论文。",link:"theory"},{time:"持续",title:"完成跨学科项目",goal:"用透明方法回答现实问题。",learn:"研究设计、数据或访谈、分析、写作和复现。",done:"公开材料、结果、限制与引用。",link:"projects"}],tools:[["文献与引用",[["Google Scholar","https://scholar.google.com/","检索论文和引用关系"],["JSTOR Open Content","https://about.jstor.org/oa-and-free/","查找开放学术内容"],["Zotero","https://www.zotero.org/","管理资料和引用"]]],["数据",[["Our World in Data","https://ourworldindata.org/","探索全球长期数据"],["World Bank Data","https://data.worldbank.org/","获取发展指标"],["IPUMS","https://www.ipums.org/","获取人口微观数据"]]],["分析与质性研究",[["R","https://www.r-project.org/","统计、可视化和复现"],["QGIS","https://qgis.org/","空间数据分析"],["Taguette","https://www.taguette.org/","开源质性文本编码"]]]],books:[["OpenStax Introduction to Sociology 3e","https://openstax.org/details/books/introduction-sociology-3e","社会学 · 入门","完整开放教材。"],["OpenStax Introduction to Political Science","https://openstax.org/details/books/introduction-political-science","政治学 · 入门","免费建立政治学框架。"],["OpenStax Introduction to Anthropology","https://openstax.org/details/books/introduction-anthropology","人类学 · 入门","覆盖人类学四个分支。"],["CORE Econ","https://www.core-econ.org/the-economy/","经济学 · 入门","开放、数据导向的经济学教材。"]],portals:[["MIT","MIT OCW Social Science","https://ocw.mit.edu/search/?d=Social%20Science","多学科大学课程。"],["Yale","Open Yale Social Sciences","https://oyc.yale.edu/courses","社会理论、政治和经济课程。"],["OpenStax","OpenStax Social Sciences","https://openstax.org/subjects/social-sciences","合法免费的社会科学教材。"]]};

const historyTopics:Record<string,Topic>={
 tools:t("学习工具","管理时间线、地图、文献与档案来源，区分一手和二手材料。",[]),
 methods:t("史学方法与史料","学习来源批判、语境化、比较、论证和引用。",[r("Historical Thinking Project","https://historicalthinking.ca/historical-thinking-concepts","入门","公开讲义","无需前置","用六个概念练习证据、因果、连续与变化。"),r("MIT 21H.390 Theories and Methods in History","https://ocw.mit.edu/courses/21h-390-theories-and-methods-in-the-study-of-history-fall-2022/","进阶","公开课","历史导论与写作","系统学习历史学的理论、方法和研究实践。"),r("The Programming Historian","https://programminghistorian.org/","高级","公开讲义","史学方法与基础数字工具","免费教程将数据、文本、地图和网络方法用于历史研究。")]),
 humanity:t("人类史与全球文明","以长时段视角理解人类演化、迁徙、农业、城市、国家、交换网络与全球化。",[r("Smithsonian: Introduction to Human Evolution","https://humanorigins.si.edu/education/introduction-human-evolution","入门","项目平台","无需前置","从化石、遗传和考古证据认识人类起源与迁徙。"),r("OpenStax World History Volume 1","https://openstax.org/details/books/world-history-volume-1","进阶","开放教材","人类演化与基础地理","从早期人类、农业革命到 1500 年建立全球文明框架。"),r("MIT 21H.009 The World: 1400–Present","https://ocw.mit.edu/courses/21h-009-the-world-1400-present-spring-2014/","高级","公开课","世界史概览与史料阅读","从环境、制度、阶层、种族与性别研究现代全球联系。")]),
 ancient:t("古代与中古世界","比较早期国家、帝国、宗教、贸易和社会结构。",[r("OpenStax World History Volume 1","https://openstax.org/details/books/world-history-volume-1","入门","开放教材","无需前置","从早期人类到约 1500 年的全球史。"),r("Yale Ancient History","https://oyc.yale.edu/history","进阶","公开课","世界史概览","从 Yale 课程深入希腊、罗马和中古欧洲。"),r("MIT Ancient and Medieval History","https://ocw.mit.edu/search/?q=ancient%20medieval%20history","高级","公开课","史学方法与专题阅读","通过专题课程比较文本、考古和制度证据。")]),
 modern:t("近代与现代世界","理解全球联系、帝国、革命、工业化、民族国家与战争。",[r("OpenStax World History Volume 2","https://openstax.org/details/books/world-history-volume-2","入门","开放教材","古代史概览","从约 1400 年讲到当代全球世界。"),r("Yale European Civilization, 1648–1945","https://oyc.yale.edu/history/hist-202","进阶","公开课","世界史概览","系统理解欧洲国家、革命、工业化和战争。"),r("MIT Modern History","https://ocw.mit.edu/search/?q=modern%20history","高级","公开课","史学方法与主题基础","按帝国、殖民、民族主义和全球化继续研究。")]),
 china:t("中国史","从早期国家到现代转型，结合制度、社会、思想和全球互动。",[r("复旦大学：中国历史人文地理（上）","https://mooc1.chaoxing.com/course/250474395.html","入门","公开课","无需前置","由葛剑雄讲授，从疆域、人口、民族与地域文化建立中国史的空间框架。"),r("Chinese Text Project","https://ctext.org/","入门","项目平台","无需前置","检索双语先秦与古代文本并查看原始材料。"),r("复旦大学：二十四史名篇导读（一）","https://mooc1.chaoxing.com/course/201747835.html","进阶","公开课","中国古代史概览与基础文言文","由韩昇从《史记》《汉书》《后汉书》《三国志》训练正史阅读与史料分析。"),r("Harvard ChinaX","https://pll.harvard.edu/subject/asia","进阶","公开课","世界史概览","由 Harvard 课程从考古、思想和制度理解中国历史。"),r("南京大学：从天下到世界——近代中国的历程","https://www.icourse163.org/course/NJU-1468488162","高级","公开课","中国古代史与基础史料阅读","围绕十八至十九世纪的观念、制度、贸易、外交与战争，分析中国进入现代世界的转型。"),r("China Historical GIS","https://chgis.fas.harvard.edu/","高级","项目平台","中国史、地图与数据基础","用历史地理数据研究行政区、地点和长期变化。")]),
 europe:t("欧洲史","从古典遗产、中世纪社会到国家形成、革命、工业化、帝国与欧洲一体化。",[r("Yale: The Early Middle Ages, 284–1000","https://oyc.yale.edu/history/hist-210","入门","公开课","无需前置","用完整讲座建立罗马转型、基督教、拜占庭、伊斯兰与封建欧洲的基础。"),r("Yale: European Civilization, 1648–1945","https://oyc.yale.edu/history/hist-202","进阶","公开课","欧洲古代与中古史概览","系统学习国家、启蒙、革命、工业化、民族主义与两次世界大战。"),r("Europeana Collections","https://www.europeana.eu/","高级","项目平台","史学方法、欧洲史与研究写作","以欧洲博物馆、图书馆和档案馆的数字原件完成专题研究。")]),
 japan:t("日本史","从古代国家与武家政权，到德川社会、明治维新、帝国、战后重建与当代日本。",[r("Columbia Asia for Educators: Japan","https://afe.easia.columbia.edu/tps/1000bce_jp.htm","入门","项目平台","无需前置","沿时间线阅读日本各时期概览、图像和经过整理的一手史料。"),r("MIT 21H.155 Modern Japan: 1868 to Present","https://ocw.mit.edu/courses/21h-155-modern-japan-1868-to-present-spring-2017/","进阶","公开课","东亚史或世界近代史概览","以讲义、阅读和写作任务研究近现代日本及其全球联系。"),r("MIT 21H.154 Inventing the Samurai","https://ocw.mit.edu/courses/21h-154-inventing-the-samurai-fall-2022/","高级","公开课","日本史基础；研究项目需日语","从古代至近世追踪武士阶层的形成，并分析后世如何重塑武士形象。")]),
 americas:t("美洲史","理解原住民社会、殖民、奴隶制、国家建构与社会运动。",[r("OpenStax U.S. History","https://openstax.org/details/books/us-history","入门","开放教材","无需前置","免费美国史教材并置于大西洋和全球语境。"),r("Yale American History","https://oyc.yale.edu/history","进阶","公开课","美国史概览","可选内战、革命和二十世纪专题课程。"),r("Library of Congress Digital Collections","https://www.loc.gov/collections/","高级","项目平台","史料批判与研究写作","使用照片、报刊、地图和手稿完成一手史料研究。")]),
 global:t("全球史专题","跨区域研究贸易、迁徙、疾病、环境、科技、性别与思想流动。",[r("World History Commons","https://worldhistorycommons.org/","入门","项目平台","世界史概览","按主题阅读原始材料和教学模块。"),r("MIT Global History","https://ocw.mit.edu/search/?q=global%20history","进阶","公开课","近现代史与史学方法","通过跨区域课程理解连接与比较。"),r("Our World in Data","https://ourworldindata.org/","高级","项目平台","统计与历史语境","结合长期数据分析人口、健康、能源和战争变化。")]),
 projects:t("项目与进阶方向","从一个可控问题出发，以一手史料和清晰论证完成研究。",[r("Fordham Internet History Sourcebooks","https://sourcebooks.fordham.edu/","入门","项目平台","史料批判基础","选择同一事件的数份材料进行比较。"),r("Europeana Collections","https://www.europeana.eu/","进阶","项目平台","史学方法与引用","使用欧洲数字档案策划带出处的主题展览。"),r("The Programming Historian","https://programminghistorian.org/","高级","公开讲义","史学、数据与基础编程","完成文本分析、GIS 或网络分析并公开过程。")]),
 books:t("书单与资源","集中查看开放教材、原始史料与大学课程。",[])
};
export const history:SubjectConfig={slug:"history",name:"历史",en:"HISTORY",intro:"历史学通过批判性阅读史料，解释人类社会如何变化、为何变化，以及我们能在多大程度上认识过去。",caution:"历史不是年份清单，也不是用今天的常识审判过去。始终区分史料与解释，确认作者、语境、沉默之处和相互矛盾的证据。",groups:[start,["共同基础",[["tools","学习工具"],["methods","史学方法与史料"]]],["总体与时期",[["humanity","人类史与全球文明"],["ancient","古代与中古世界"],["modern","近代与现代世界"]]],["区域历史",[["china","中国史"],["europe","欧洲史"],["japan","日本史"],["americas","美洲史"]]],["跨区域专题",[["global","全球史专题"],["projects","项目与进阶方向"],["books","书单与资源"]]]],topics:historyTopics,phases:[{time:"1 个月",title:"先学会阅读史料",goal:"区分一手材料、二手研究与公共叙事。",learn:"出处、语境、立场、互证、时间线和规范引用。",done:"完成一份两种史料的对读笔记。",link:"methods"},{time:"3–5 个月",title:"建立人类史与世界史骨架",goal:"掌握主要时代、区域和全球联系。",learn:"人类演化、迁徙、农业、国家、宗教、贸易与工业化。",done:"不用教材画出跨区域时间线并解释关键转折。",link:"humanity"},{time:"2–4 个月",title:"深化一个区域",goal:"在长时段中理解制度、社会和思想变化。",learn:"从中国、欧洲、日本或美洲中选择一个区域，完成专题课程与史料阅读。",done:"围绕一个问题写出有史料支持的短论文。",link:"china"},{time:"2–4 个月",title:"用主题连接区域",goal:"避免把各国历史学成孤岛。",learn:"迁徙、环境、疾病、科技、性别与全球交换。",done:"比较两个地区对同一全球过程的不同经验。",link:"global"},{time:"持续",title:"完成独立历史研究",goal:"形成问题、史料、论证和限制意识。",learn:"档案检索、文献综述、分析、写作或数字史学。",done:"发布带完整出处和方法说明的研究成果。",link:"projects"}],tools:[["资料管理",[["Zotero","https://www.zotero.org/","保存史料、研究和引用"],["Tropy","https://tropy.org/","整理档案照片及元数据"],["TimelineJS","https://timeline.knightlab.com/","制作可核查的叙事时间线"]]],["数字档案",[["Internet Archive","https://archive.org/","检索公版书刊和影像"],["Library of Congress","https://www.loc.gov/collections/","使用美国数字馆藏"],["Europeana","https://www.europeana.eu/","检索欧洲文化遗产"]]],["空间与文本",[["QGIS","https://qgis.org/","制作历史地图"],["Voyant Tools","https://beta.voyant-tools.org/","探索文本语料（主站迁移期间使用官方 Beta）"],["The Programming Historian","https://programminghistorian.org/","学习数字史学方法"]]]],books:[["OpenStax World History Volume 1","https://openstax.org/details/books/world-history-volume-1","世界史至 1500 · 入门","全球视角的开放教材。"],["OpenStax World History Volume 2","https://openstax.org/details/books/world-history-volume-2","世界史 1400 至今 · 入门","现代世界史开放教材。"],["OpenStax U.S. History","https://openstax.org/details/books/us-history","美国史 · 入门","免费完整教材。"]],portals:[["Yale","Open Yale History","https://oyc.yale.edu/history","古代、欧洲、美国等完整课程。"],["MIT","MIT OCW History","https://ocw.mit.edu/search/?d=History","地区史、全球史与史学方法。"],["Columbia","Asia for Educators","https://afe.easia.columbia.edu/","东亚历史分期、教学模块与一手史料。"],["OpenStax","OpenStax History","https://openstax.org/subjects/humanities","免费世界史与美国史教材。"]]};
