import{r,type Phase,type Resource,type SubjectConfig,type Topic}from"./subjectTypes";

type Course=[string,string,string,Resource[]];
type Track={slug:string;name:string;en:string;intro:string;caution:string;courses:Course[];tools:SubjectConfig["tools"];books:SubjectConfig["books"];portals:SubjectConfig["portals"]};
const start=["开始之前",[["intro","本站目的"],["how","如何使用本站"],["plan","学习规划"]]] as const;
const phaseSettings:Record<string,Record<string,{time:string;mode?:Phase["mode"];title?:string}>>={
 linguistics:{foundations:{time:"2–3 个月"},sound:{time:"2–3 个月"},grammar:{time:"3–4 个月"},"meaning-change":{time:"3–4 个月"},computational:{time:"按方向 4–6 个月",mode:"choice",title:"选择计算语言学或其他专门方向"}},
 chinese:{modern:{time:"2–3 个月"},grammar:{time:"2–3 个月"},classical:{time:"5–8 个月"},"history-dialects":{time:"按方向 4–6 个月",mode:"choice",title:"选择汉语史、音韵或方言方向"}},
 english:{"sound-listening":{time:"2–4 周",title:"诊断水平并启动语音与听力"},"grammar-vocabulary":{time:"同步进行 12–20 个月",mode:"parallel"},reading:{time:"同步进行 12–20 个月",mode:"parallel"},communication:{time:"同步进行 12–20 个月",mode:"parallel"}}
};

const makeTrack=(track:Track):SubjectConfig=>{
 const topics:Record<string,Topic>={
  tools:{title:"学习工具",intro:`围绕${track.name}建立检索、记录、分析与练习环境。`,resources:[]},
  projects:{title:"项目与进阶方向",intro:`用${track.name}的真实材料完成可检查的分析、表达或研究项目。`,resources:track.courses.map(([, , ,resources])=>resources[0])},
  books:{title:"书单与资源",intro:"集中查看开放教材、大学官方课程和可靠语言资源。",resources:[]}
 };
 track.courses.forEach(([id,title,intro,resources])=>{topics[id]={title,intro,resources}});
 const phases:Phase[]=track.courses.map(([id,title,intro])=>{const setting=phaseSettings[track.slug]?.[id];return{
  time:setting?.time??"2–4 个月",title:setting?.title??`学习${title}`,goal:intro,
  learn:`完成${title}的一套主资源，配合练习、材料分析和阶段复盘。`,
  done:`能不用原文解释${title}的核心概念，并提交一份可检查的练习或作品。`,link:id,mode:setting?.mode??"core"
 }});
 phases.push({time:"从第二阶段持续",title:"完成独立项目",goal:"把分散知识转化为真实的分析与表达能力。",learn:"问题、材料、方法、证据、修订与反思。",done:"发布一份带来源、过程和自我评估的语言项目。",link:"projects",mode:"ongoing"});
 return{slug:`language/${track.slug}`,name:track.name,en:track.en,intro:track.intro,caution:track.caution,groups:[start,["起点",[["tools","学习工具"]]],["核心课程",track.courses.map(([id,title])=>[id,title] as const)],["实践与资源",[["projects","项目与进阶方向"],["books","书单与资源"]]]],topics,phases,tools:track.tools,books:track.books,portals:track.portals};
};

export const linguistics=makeTrack({slug:"linguistics",name:"语言学",en:"LINGUISTICS",intro:"语言学以可检验的证据研究人类语言的声音、结构、意义、使用、习得与变化，而不是只学习某一种语言。",caution:"语言学分析不能只凭母语直觉。要区分描写与规范，记录数据来源，比较不同分析，并尊重所有语言、方言和使用者。",courses:[
 ["foundations","语言学导论","建立语言作为认知与社会系统的整体框架，并学习从数据提出假设。",[r("Essentials of Linguistics 2e","https://opentextbc.ca/essentialsoflinguistics2/","入门","开放教材","无需前置","带视频、练习和术语解释的完整开放教材，适合第一次系统接触语言学。"),r("MIT 24.900 Introduction to Linguistics","https://ocw.mit.edu/courses/24-900-introduction-to-linguistics-spring-2022/","进阶","公开课","无需前置","以视频、讲义和问题集覆盖形态、语音、音系、句法、语义、变化和习得。"),r("MIT Linguistics OpenCourseWare","https://ocw.mit.edu/search/?d=Linguistics","高级","公开课","语言学导论","按音系、句法、语义、语言哲学和心理语言学继续选择高阶课程。")]],
 ["sound","语音学与音系学","研究语音如何产生、感知、测量并组成语言特有的声音系统。",[r("UCLA Phonetics Lab Archive","https://www.phonetics.ucla.edu/","入门","项目平台","语言学导论","用真实录音、国际音标和多语言材料练习听辨与转写。"),r("MIT 24.901 Introduction to Phonology","https://ocw.mit.edu/courses/24-901-introduction-to-phonology-spring-2026/","进阶","公开课","语言学导论与国际音标","通过数据集、规则和约束分析音位、分布、音变与音系表征。"),r("MIT 24.915 Linguistic Phonetics","https://ocw.mit.edu/courses/24-915-linguistic-phonetics-fall-2015/","高级","公开课","语音学、音系学与基础统计","连接发音、声学、感知和实验方法，包含讲义与问题集。")]],
 ["grammar","形态学与句法学","分析词的内部结构、句子的层级关系以及跨语言语法差异。",[r("Essentials of Linguistics: Morphology and Syntax","https://opentextbc.ca/essentialsoflinguistics2/","入门","开放教材","语言学导论","通过开放教材的形态与句法单元学习切分、成分、短语结构和句法树。"),r("MIT 24.902 Language and its Structure II: Syntax","https://ocw.mit.edu/courses/24-902-language-and-its-structure-ii-syntax-fall-2015/","进阶","公开课","语言学导论","用跨语言数据和问题集分析层级结构、论元、移位与语序差异。"),r("MIT Advanced Syntax Courses","https://ocw.mit.edu/search/?q=syntax","高级","公开课","句法学、逻辑与成熟证明能力","继续研究句法理论、句法—语义接口和语言类型差异。")]],
 ["meaning-change","语义、语用与语言变化","理解句义、语境、会话推理、方言、语言接触与历史演变。",[r("MIT 24.903 Semantics and Pragmatics","https://ocw.mit.edu/courses/24-903-language-and-its-structure-iii-semantics-and-pragmatics-spring-2005/","入门","公开课","语言学导论与基础逻辑","从真值条件、量化和语境进入形式语义与语用推理。"),r("WALS Online","https://wals.info/","进阶","项目平台","语言类型学与基础统计","利用世界语言结构特征数据库比较语序、声音和语法现象。"),r("Glottolog","https://glottolog.org/","高级","项目平台","历史语言学与文献检索","核查语言分类、地理分布和参考文献，开展语言亲缘与多样性研究。")]],
 ["computational","计算语言学与语料方法","用语料、统计和机器学习研究文本与语音，同时检验模型的语言学假设。",[r("Natural Language Processing with Python","https://www.nltk.org/book/","入门","开放教材","Python 基础","通过可运行示例学习分词、标注、分类、句法分析和语料统计。"),r("Stanford CS224N","https://web.stanford.edu/class/cs224n/","进阶","公开课","Python、线性代数、概率与机器学习","系统学习词向量、序列模型、Transformer 与现代自然语言处理。"),r("Speech and Language Processing","https://web.stanford.edu/~jurafsky/slp3/","高级","开放教材","NLP、概率与深度学习","Stanford 作者公开教材，连接语言学、语音、统计模型和大语言模型。")]]
],tools:[["语音与转写",[["Praat","https://www.fon.hum.uva.nl/praat/","测量、标注和可视化语音"],["IPA Chart","https://www.internationalphoneticassociation.org/IPAcharts/IPA_chart_orig/IPA_charts_E.html","查阅国际音标官方表"]]],["语料与类型",[["WALS","https://wals.info/","比较世界语言结构"],["Glottolog","https://glottolog.org/","查询语言分类与文献"],["Universal Dependencies","https://universaldependencies.org/","使用跨语言句法树库"]]],["计算与研究",[["Python + NLTK","https://www.nltk.org/","处理文本语料"],["Zotero","https://www.zotero.org/","管理语言学文献"]]]],books:[["Essentials of Linguistics 2e","https://opentextbc.ca/essentialsoflinguistics2/","导论 · 入门","完整开放语言学教材。"],["Speech and Language Processing","https://web.stanford.edu/~jurafsky/slp3/","计算语言学 · 高级","公开教材草稿。"]],portals:[["MIT","MIT Linguistics Curriculum","https://catalog.mit.edu/degree-charts/linguistics-philosophy-course-24-2/","参考 MIT 语言学本科课程的核心结构与进阶方向。"],["MIT","MIT OCW Linguistics","https://ocw.mit.edu/search/?d=Linguistics","语言学导论及音系、句法、语义等公开课程。"]]});

export const chinese=makeTrack({slug:"chinese",name:"汉语",en:"CHINESE LANGUAGE",intro:"汉语路线研究现代汉语的语音、文字、词汇和语法，并通过古代汉语、方言和语料理解汉语的历史层次与实际使用。",caution:"不要把规范标准等同于全部汉语。普通话、书面语、方言和古代汉语各有语境；分析时应以真实材料为依据，并区分语言事实与价值判断。",courses:[
 ["modern","现代汉语：语音、文字与词汇","从普通话语音系统、汉字结构和词汇构成建立现代汉语的描写基础。",[r("MIT Learning Chinese: A Foundation Course in Mandarin","https://ocw.mit.edu/courses/res-21g-003-learning-chinese-a-foundation-course-in-mandarin-spring-2011/","入门","公开课","无需前置","用系统音频和教材重新观察声母、韵母、声调、汉字和基础词汇。"),r("北京大学现代汉语课程资源","https://resource.pku.edu.cn/index.php?id=331&r=course%2Fdetail","进阶","公开课","熟练使用汉语","北大中文系主干课，内容覆盖总论、语音、文字、词汇、语法和修辞。"),r("Unicode Unihan Database","https://www.unicode.org/charts/unihan.html","高级","项目平台","汉字学与数据检索","查询汉字编码、读音和字源字段，建立可复查的汉字数据分析。")]],
 ["grammar","现代汉语：语法与修辞","分析短语、句法、虚词、信息结构和修辞选择，并用语料验证语感。",[r("北京大学现代汉语课程资源","https://resource.pku.edu.cn/index.php?id=331&r=course%2Fdetail","入门","公开课","现代汉语语音、文字与词汇","按北大课程下半部分进入语法和修辞。"),r("北京大学 CCL 语料库","http://ccl.pku.edu.cn:8080/ccl_corpus/","进阶","项目平台","基础语法与检索意识","检索真实上下文，比较词语搭配、句式和历时用法。"),r("北京语言大学 BCC 语料库","http://bcc.blcu.edu.cn/","高级","项目平台","语料方法与基础统计","利用多领域、大规模语料研究词汇、构式和语言变异。")]],
 ["classical","古代汉语与文言阅读","学习古汉语词义、语法、文字、音韵和典籍常识，形成可靠的文言阅读方法。",[r("南京大学古代汉语精品课程","https://www.njude.com.cn/jingpin2008/gdhy/kcms-2.htm","入门","公开课","现代汉语与基础文言阅读","南京大学中文专业基础课程，系统学习文字、音韵、词汇、语法、诗律与古书注解。"),r("北京语言大学：古代汉语","https://www.icourse163.org/course/BLCU-1206312837","进阶","公开课","基础文言阅读","系统讲授古代名篇以及文字、词汇、语法、音韵和典籍知识。"),r("Chinese Text Project","https://ctext.org/","高级","项目平台","古代汉语与训诂基础","使用原文、异文、词典和检索功能核查先秦两汉典籍。")]],
 ["history-dialects","汉语史、音韵与方言","理解上古至现代的语音、词汇和语法变化，并学习记录方言差异。",[r("北京大学中文系汉语言专业教学手册","https://ccl.pku.edu.cn/all/download/static/uploads/pdf/e96006dcf5.pdf","入门","公开讲义","现代汉语与古代汉语基础","参考北大课程体系理解汉语史、音韵、方言和语法研究之间的关系。"),r("中国语言资源保护工程","https://zhongguoyuyan.cn/","进阶","项目平台","语音学、方言学与田野伦理","观察各地语言资源与有声材料，学习方言调查和保存的基本规范。"),r("Wiktionary Chinese Entries","https://zh.wiktionary.org/","高级","项目平台","音韵学、文献检索与资料核查","比较中古拟音、方言读音和词源条目，并回查其引用来源。")]]
],tools:[["字词与典籍",[["汉典","https://www.zdic.net/","查询字词、古籍和音韵资料"],["Chinese Text Project","https://ctext.org/","检索古代典籍"],["Unicode Unihan","https://www.unicode.org/charts/unihan.html","查询汉字编码数据"]]],["现代语料",[["CCL 语料库","http://ccl.pku.edu.cn:8080/ccl_corpus/","检索现代与古代汉语语料"],["BCC 语料库","http://bcc.blcu.edu.cn/","分析多领域汉语用法"]]],["语音与研究",[["Praat","https://www.fon.hum.uva.nl/praat/","分析普通话和方言录音"],["Zotero","https://www.zotero.org/","管理汉语研究资料"]]]],books:[["Learning Chinese: A Foundation Course","https://ocw.mit.edu/courses/res-21g-003-learning-chinese-a-foundation-course-in-mandarin-spring-2011/","现代汉语 · 入门","MIT 完整教材与音频。"],["Chinese Text Project","https://ctext.org/","古代汉语 · 进阶","可检索的开放典籍资料库。"]],portals:[["北大","北京大学中文系汉语言专业课程","https://ccl.pku.edu.cn/all/download/static/uploads/pdf/e96006dcf5.pdf","参考现代汉语、古代汉语、音韵、方言和语言学课程结构。"],["北大","北京大学现代汉语课程资源","https://resource.pku.edu.cn/index.php?id=331&r=course%2Fdetail","现代汉语主干课公开资源。"],["华文慕课","北京大学华文慕课","https://www.chinesemooc.org/","检索北京大学及合作高校的中文公开课程。"]]});

export const english=makeTrack({slug:"english",name:"英语",en:"ENGLISH",intro:"英语路线以可理解输入和真实输出为主线，分别训练语音听力、语法词汇、深度阅读以及写作与口语，而不是把背单词当作全部学习。",caution:"英语水平来自长期使用，不来自一次性刷课。每周都应包含听、读、说、写和反馈；工具可以纠错，但不能代替你组织观点和反复修订。",courses:[
 ["sound-listening","语音与听力","建立英语音素、重音、节奏和连读意识，并逐步适应真实语速和不同口音。",[r("University of Iowa Sounds of Speech","https://soundsofspeech.uiowa.edu/","入门","项目平台","无需前置","用动画、视频和音频理解美式英语元音与辅音如何产生。"),r("BBC Learning English","https://www.bbc.co.uk/learningenglish/","进阶","项目平台","基础词汇与语法","通过分级新闻、发音和系列节目进行稳定的真实听力输入。"),r("MIT High-Intermediate Academic Communication","https://ocw.mit.edu/courses/21g-213-high-intermediate-academic-communication-spring-2004/","高级","公开课","英语 B1–B2","把精听、讨论、演讲和学术表达结合起来，配有作业示例。")]],
 ["grammar-vocabulary","语法、词汇与语料","从真实语料理解词类、短语、从句、搭配和语域，而不是孤立记规则。",[r("British Council LearnEnglish Grammar","https://learnenglish.britishcouncil.org/free-resources/grammar","入门","项目平台","基础英语阅读","按 A1–A2、B1–B2、C1 分级学习语法，并配有免费互动练习。"),r("Cambridge Dictionary: English Grammar","https://dictionary.cambridge.org/grammar/british-grammar/","入门","开放教材","基础英语阅读","按主题查阅清晰的规则、常见错误和真实语料例句。"),r("Purdue OWL: Grammar","https://owl.purdue.edu/owl/general_writing/grammar/index.html","进阶","公开讲义","基础英语写作","通过大学写作中心的语法、标点和句子结构指南修正常见问题。"),r("English-Corpora.org","https://www.english-corpora.org/","高级","项目平台","语料检索与基础统计","比较不同年代、地区和语域中的词汇与语法使用。"),r("University of Manchester Academic Phrasebank","https://www.phrasebank.manchester.ac.uk/?lang=en","高级","公开讲义","英语 B2 与基础写作","学习学术写作中引言、论证、转折、结果与结论的常用表达，并按语境改写使用。")]],
 ["reading","阅读与论证理解","从分级材料过渡到长文和学术文本，识别主张、证据、结构、语气和隐含前提。",[r("USA Learns English Courses","https://www.usalearns.org/","入门","公开课","无需前置","用分级听读材料和练习建立高频词汇与基本理解。"),r("MIT OpenCourseWare Reading and Writing","https://ocw.mit.edu/search/?q=critical%20reading%20writing","进阶","公开课","英语 B1–B2","选择包含阅读回应、文本分析和写作任务的 MIT 课程。"),r("Harvard College Writing Center: Reading Strategies","https://writingcenter.fas.harvard.edu/","高级","公开讲义","英语 B2–C1","借助分析性阅读与论证写作指南练习提出问题、概括和评估证据。")]],
 ["communication","写作、口语与修订","学习围绕受众组织观点，通过反馈反复修订文章，并在讨论和演讲中清楚表达。",[r("Harvard Strategies for Essay Writing","https://writingcenter.fas.harvard.edu/pages/strategies-essay-writing","入门","公开讲义","能够阅读一般英语文章","从分析问题、论点、段落、过渡、反驳到结论建立完整写作流程。"),r("MIT 21G.213 High-Intermediate Academic Communication","https://ocw.mit.edu/courses/21g-213-high-intermediate-academic-communication-spring-2004/","进阶","公开课","英语 B1–B2","通过短文、备忘录、讨论、辩论和演讲同时训练书面与口头表达。"),r("MIT 21G.225 Advanced Workshop in Writing","https://ocw.mit.edu/courses/21g-225-advanced-workshop-in-writing-for-science-and-engineering-els-spring-2016/","高级","公开课","英语 B2–C1 与专业知识","面向科学和工程语境训练报告、论证、同行反馈和专业演讲。")]]
],tools:[["发音与听力",[["Sounds of Speech","https://soundsofspeech.uiowa.edu/","观察英语音素的发音方式"],["YouGlish","https://youglish.com/","在真实视频中检索发音与用法"]]],["词典与语料",[["Cambridge Dictionary","https://dictionary.cambridge.org/","查询释义、发音和例句"],["English-Corpora","https://www.english-corpora.org/","比较语域、年代和地区"]]],["写作与复习",[["LanguageTool","https://languagetool.org/","辅助检查语法与风格"],["Anki","https://apps.ankiweb.net/","间隔复习词汇和例句"],["Zotero","https://www.zotero.org/","管理阅读和引用"]]]],books:[["British Council LearnEnglish Grammar","https://learnenglish.britishcouncil.org/free-resources/grammar","语法 · 入门","按英语等级提供免费讲解和互动练习。"],["Cambridge English Grammar","https://dictionary.cambridge.org/grammar/british-grammar/","语法 · 进阶","基于真实语料的语法参考。"],["Harvard Strategies for Essay Writing","https://writingcenter.fas.harvard.edu/pages/strategies-essay-writing","写作 · 进阶","公开的学术写作指南。"]],portals:[["MIT","MIT Global Languages","https://ocw.mit.edu/search/?d=Global%20Studies%20and%20Languages","检索学术沟通、写作和英语语言课程。"],["Harvard","Harvard College Writing Center","https://writingcenter.fas.harvard.edu/","学术阅读、论证和写作公开指南。"],["British Council","LearnEnglish","https://learnenglish.britishcouncil.org/","分级的免费英语学习材料与练习。"]]});

export const languageTracks=[linguistics,chinese,english];
