import {r,type SubjectConfig,type Topic} from "./subjectTypes";
const t=(title:string,intro:string,resources:ReturnType<typeof r>[]):Topic=>({title,intro,resources});
const start=["开始之前",[["plan","学习规划"]]] as const;
const topics:Record<string,Topic>={
 tools:t("学习工具","获取合法文本、建立阅读批注、管理版本、引用和写作。",[]),
 reading:t("细读与文学写作","从语言、形式、叙述、意象和语境提出可由文本支持的解释。",[r("The Word on College Reading and Writing","https://open.umn.edu/opentextbooks/textbooks/471","入门","开放教材","无需前置","学习批判性阅读、文本分析、论点、证据与修改。"),r("MIT Reading Fiction","https://ocw.mit.edu/search/?q=reading%20fiction","进阶","公开课","基础阅读与写作","通过小说练习叙述视角、结构和形式分析。"),r("Yale Modern Poetry","https://oyc.yale.edu/english/engl-310","高级","公开课","诗歌细读与文学史基础","用完整大学课程深化韵律、声音和现代主义语境。")]),
 writing:t("写作","从观察、表达和修改开始，逐步掌握非虚构写作、短篇小说与类型文学创作，并通过持续反馈形成个人作品。",[r("OpenStax Writing Guide with Handbook","https://openstax.org/details/books/writing-guide","入门","开放教材","无需前置","从写作过程、段落和修订入手，学习叙事、分析、论证、研究与引用等常用体裁。"),r("MIT Writing and Reading Short Stories","https://ocw.mit.edu/courses/21w-755-writing-and-reading-short-stories-spring-2012/","进阶","公开课","基础阅读与写作","通过范文、写作练习和工作坊训练情节、人物、视角、场景与修改。"),r("MIT Writing Science Fiction","https://ocw.mit.edu/courses/21w-759-writing-science-fiction-spring-2016/","高级","公开课","短篇小说写作与文学细读","围绕类型规则、世界构建和叙事技法完成两篇作品，并依据工作坊反馈重写。")]),
 theory:t("文学理论","比较形式主义、结构主义、解释学、精神分析、马克思主义、女性主义和后殖民理论。",[r("Purdue OWL: Writing a Literary Analysis","https://owl.purdue.edu/owl/resources/teaching_resources/documents/new-writing-a-lit-analysis-08202025.pdf","入门","公开讲义","细读基础","用文本证据、分析和批评视角组织文学论文。"),r("Yale ENGL 300 Introduction to Theory of Literature","https://oyc.yale.edu/english/engl-300","进阶","公开课","文学阅读与基础哲学","系统梳理二十世纪文学理论。"),r("Stanford Encyclopedia: Philosophy of Literature","https://plato.stanford.edu/entries/philosophy-literature/","高级","公开讲义","文学理论与哲学阅读","从权威综述和参考文献进入美学与解释问题。")]),
 world:t("中外文学","把中国文学置于世界文学的共同地图中，沿体裁、时代与文化交流阅读诗歌、散文、小说和戏剧。",[r("Chinese Text Project","https://ctext.org/","入门","项目平台","现代汉语","免费检索先秦至古代典籍及部分译文，建立中国古典文学与思想的原典入口。"),r("World Literature I: Beginnings to 1650","https://open.umn.edu/opentextbooks/textbooks/409","入门","开放教材","无需前置","经同行评审的开放选集，用跨区域文本补充全球文学史框架。"),r("MIT Chinese Literature","https://ocw.mit.edu/search/?q=Chinese%20literature","进阶","公开课","中国史与文学细读","通过大学课程连接中国作品、体裁和历史语境。"),r("MIT Foundations of World Culture II","https://ocw.mit.edu/courses/21l-002x-foundations-of-world-culture-ii-world-literatures-and-texts-spring-2012/","进阶","公开课","细读与世界史概览","从早期现代到近现代比较不同文化的重要文本。"),r("Harvard Chinese Humanities","https://pll.harvard.edu/subject/asia","高级","公开课","中国文学史与文言阅读","从诗学、思想和艺术传统开展中国人文专题研究。"),r("MIT World Literatures","https://ocw.mit.edu/search/?q=world%20literatures","高级","公开课","文学理论与比较阅读","按旅行、殖民、翻译和全球流动深化跨文化研究。")]),
 comparative:t("比较文学与翻译","研究文本跨语言、媒介和文化传播时发生的变化。",[r("Compact Anthology of World Literature","https://open.umn.edu/opentextbooks/textbooks/410","入门","开放教材","世界文学概览","用跨文化选集练习共同主题比较。"),r("MIT Literature and Translation","https://ocw.mit.edu/search/?q=literature%20translation","进阶","公开课","至少一门外语更佳","研究翻译选择、不可译性和文本流通。"),r("Harvard World Literature","https://pll.harvard.edu/subject/literature","高级","公开课","比较文学与理论","从全球传播、经典形成和阅读制度深化研究。")]),
 modern:t("现代与当代文学","理解现代主义、殖民经验、身份、媒介与全球化如何改变文学。",[r("Compact Anthology of World Literature II","https://open.umn.edu/opentextbooks/textbooks/1236","入门","开放教材","世界文学概览","开放选集覆盖十七世纪至当代。"),r("Yale American Novel Since 1945","https://oyc.yale.edu/english/engl-291","进阶","公开课","小说细读与现代史","通过完整课程研究战后小说和阅读方法。"),r("MIT Contemporary Literature","https://ocw.mit.edu/search/?q=contemporary%20literature","高级","公开课","文学理论与现代史","按后殖民、技术、生态和身份进入专题。")]),
 digital:t("数字人文与文学研究","用文本分析、版本、地图和网络方法辅助解释，而非取代细读。",[r("The Programming Historian","https://programminghistorian.org/","入门","公开讲义","基础数字工具","逐步学习文本清理、分析和可视化。"),r("Voyant Tools","https://beta.voyant-tools.org/","进阶","项目平台","文学研究与语料基础","探索词频、搭配和主题后回到文本验证。"),r("Stanford Literary Lab","https://litlab.stanford.edu/","高级","项目平台","文学理论、数据与编程","理解计算方法、文学史问题与可复现研究。")]),
 projects:t("项目与进阶方向","用细读论文、比较专题、数字展览或开放注释形成作品。",[r("Standard Ebooks","https://standardebooks.org/","入门","项目平台","基础文学阅读","选择公版作品做规范批注和版本比较。"),r("Project Gutenberg","https://www.gutenberg.org/","进阶","项目平台","文学史、引用与版本意识","围绕一个主题建立带出处的开放阅读单。"),r("Stanford Literary Lab Projects","https://litlab.stanford.edu/","高级","项目平台","研究问题、文学理论和数字方法","参考公开研究设计可复现的语料或数字文学项目。")]),
 books:t("书单与资源","集中查看开放选集、大学课程和公版文本。",[])
};
export const literature:SubjectConfig={slug:"literature",name:"文学",en:"LITERATURE",intro:"文学研究通过细读、历史语境、理论比较与写作实践，理解语言如何塑造经验、想象、身份与社会世界。",caution:"阅读量不等于研究能力，写作量也不等于作品质量。阅读解释必须回到具体文本；创作则要经过观察、草稿、反馈和多轮修改，并尊重引用、版权与真实经验的边界。",groups:[start,["基础",[["tools","学习工具"],["reading","细读与文学写作"],["writing","写作"],["theory","文学理论"]]],["文学传统",[["world","中外文学"],["modern","现代与当代文学"]]],["比较与实践",[["comparative","比较文学与翻译"],["digital","数字人文与文学研究"],["projects","项目与进阶方向"],["books","书单与资源"]]]],topics,phases:[{time:"1–2 个月",title:"建立细读与写作习惯",goal:"从感想转向可验证的文本解释，并用持续写作训练清晰表达。",learn:"叙述、声音、意象、修辞、形式、批注、自由写作和修改。",done:"完成一篇以文本证据为中心的短评，以及一篇经过修改的短作。",link:"writing"},{time:"3–5 个月",title:"建立文学史地图",goal:"认识体裁、传统和时代变化。",learn:"诗歌、戏剧、小说；中国与世界文学代表作品。",done:"制作一条作品、历史与体裁相连的时间线。",link:"world"},{time:"2–4 个月",title:"学习理论工具",goal:"理解不同解释框架提出的问题。",learn:"形式、结构、性别、阶级、殖民、读者与历史。",done:"用两种理论比较同一文本并说明局限。",link:"theory"},{time:"2–4 个月",title:"进行跨文化比较",goal:"关注翻译、流通和权力关系。",learn:"比较文学、翻译、改编和世界文学。",done:"完成一篇跨语言或跨媒介比较文章。",link:"comparative"},{time:"持续",title:"形成独立研究或创作作品",goal:"把问题、文本、语境和方法组织成论证或作品。",learn:"文献、版本、数字工具、创作、工作坊和修订。",done:"公开一篇论文、短篇作品、注释集或数字展览。",link:"projects"}],tools:[["阅读与文本",[["Standard Ebooks","https://standardebooks.org/","高质量公版电子书"],["Project Gutenberg","https://www.gutenberg.org/","检索公版作品"],["Internet Archive","https://archive.org/","查找历史版本和扫描本"]]],["批注与引用",[["Hypothesis","https://web.hypothes.is/","网页协作批注"],["Zotero","https://www.zotero.org/","管理作品、研究和引用"],["Obsidian","https://obsidian.md/","连接作品、概念和读书笔记"]]],["数字研究",[["Voyant Tools","https://beta.voyant-tools.org/","文本探索与可视化（主站迁移期间使用官方 Beta）"],["AntConc","https://www.laurenceanthony.net/software/antconc/","语料检索与搭配分析"],["The Programming Historian","https://programminghistorian.org/","学习数字人文方法"]]]],books:[["World Literature I","https://open.umn.edu/opentextbooks/textbooks/409","世界文学 · 入门","同行评审开放选集。"],["Writing Guide with Handbook","https://openstax.org/details/books/writing-guide","写作 · 入门","涵盖多种体裁、写作过程、修订与引用的开放教材。"],["Compact Anthology of World Literature II","https://open.umn.edu/opentextbooks/textbooks/1236","现代文学 · 入门","覆盖十七世纪至当代。"],["Literature, the Humanities, and Humanity","https://open.umn.edu/opentextbooks/textbooks/204","细读 · 入门","开放文学导读。"]],portals:[["Yale","Open Yale Literature","https://oyc.yale.edu/courses","理论、诗歌、小说与经典作家课程。"],["MIT","MIT OCW Literature","https://ocw.mit.edu/search/?d=Literature","世界文学、比较文学和专题课程。"],["OEN","Open Textbook Library Literature","https://open.umn.edu/opentextbooks/","开放选集和文学写作教材。"]]};
