import {mathTopics} from "./mathData";
import {MathHeader,MathSide} from "./MathHome";
import {kindLabel,levelLabel,pick,prerequisiteLabel,resourceSummary,topicLabel,useLanguage} from "./i18n";
const tools=[
 ["可视化与直觉",[["Desmos","https://www.desmos.com/calculator","函数、方程和参数变化的交互图像"],["GeoGebra","https://www.geogebra.org/","几何、代数、微积分和三维可视化"]]],
 ["符号与数值计算",[["Wolfram Alpha","https://www.wolframalpha.com/","核对计算、探索例子；不要直接抄写结果"],["SageMath","https://www.sagemath.org/","免费的开源数学计算系统"],["SymPy","https://www.sympy.org/","在 Python 中进行符号计算"]]],
 ["概率、优化与建模",[["SciPy","https://scipy.org/","进行优化、积分、微分方程和统计计算"],["CVXPY","https://www.cvxpy.org/","用 Python 表达和求解凸优化问题"],["NetworkX","https://networkx.org/","构建、分析和可视化复杂网络"]]],
 ["严格证明与形式化",[["Lean","https://lean-lang.org/","用形式化语言编写和验证数学证明"],["Theorem Proving in Lean 4","https://leanprover.github.io/theorem_proving_in_lean4/","免费学习 Lean 的逻辑、类型论与证明方法"]]],
 ["书写与研究",[["Overleaf","https://www.overleaf.com/","在线编写 LaTeX 数学文档"],["LaTeX Project","https://www.latex-project.org/","规范排版公式、证明和报告"],["Jupyter","https://jupyter.org/","把推导、代码、图表和说明放在同一份笔记中"]]]
] as const;
const mark=(kind:string)=>kind.includes("教材")?"book":kind.includes("讲义")||kind.includes("项目")?"paper":"course";

export default function MathTopicPage({slug}:{slug:string}){const{language}=useLanguage(),english=language==="en",topic=mathTopics[slug],pageTitle=topicLabel(slug,topic?.title??slug);if(!topic)return <main><h1>{pick(language,"页面不存在","Page not found")}</h1></main>;if(slug==="books")return null;return <div className="shell"><MathHeader/><MathSide active={slug}/><main><section className="hero"><small>SELF-TAUGHT MATHEMATICS / {english?pageTitle:topic.title}</small><h1>{english?pageTitle:topic.title}</h1><p>{english?`Build a working understanding of ${pageTitle} through selected open courses, textbooks, proofs, computation, and practical work.`:topic.intro}</p></section>{slug==="tools"?<div className="tool-sections">{tools.map(([title,items],index)=><section key={title}><h2>{english?`Tool set ${String(index+1).padStart(2,"0")}`:title}</h2><div className="tool-list">{items.map(([name,url,note])=><p key={name}><a href={url} target="_blank" rel="noreferrer">{name}</a><span>{english?`: Use ${name} to explore, verify, or communicate mathematical work.`:`：${note}`}</span></p>)}</div></section>)}</div>:<section><h2>{pick(language,"分级精选资源","Selected Resources by Level")}</h2><div className="cards">{topic.resources.map(resource=><article className="card" key={resource.name}><i className={`resource-mark ${mark(resource.kind)}`} aria-hidden="true"/><div><small>{english?`${kindLabel(resource.kind)} · ${levelLabel(resource.level)}`:`${resource.kind} · ${resource.level}`}</small><h3><a href={resource.url} target="_blank" rel="noreferrer">{resource.name}</a></h3><p>{english?resourceSummary(resource.name,pageTitle,resource.kind):resource.description}</p><dl><div><dt>{pick(language,"难度","Level")}</dt><dd>{english?levelLabel(resource.level):resource.level}</dd></div><div><dt>{pick(language,"前置要求","Prerequisites")}</dt><dd>{english?prerequisiteLabel(resource.level):resource.pre}</dd></div></dl></div></article>)}</div></section>}</main></div>}
