import {r,type SubjectConfig,type Topic} from "./subjectTypes";
const t=(title:string,intro:string,resources:ReturnType<typeof r>[]):Topic=>({title,intro,resources});
const start=["开始之前",[["plan","学习规划"]]] as const;
const chemistryTopics:Record<string,Topic>={
 tools:t("学习工具","用结构绘图、数据库、计算和实验记录理解物质变化。",[]),
 foundations:t("数学与物理基础","补齐单位、代数、函数、能量和原子尺度的基本语言。",[r("OpenStax Chemistry 2e: Essential Ideas","https://openstax.org/books/chemistry-2e/pages/1-introduction","入门","开放教材","无需前置","从测量、单位、物质分类和化学计量开始。"),r("MIT 5.111SC Review Materials","https://ocw.mit.edu/courses/5-111sc-principles-of-chemical-science-fall-2014/pages/unit-i-the-atom/lecture-1/","进阶","公开课","高中代数","用复习题检查方程、摩尔和有效数字基础。"),r("MIT Mathematics for Chemistry","https://ocw.mit.edu/search/?q=mathematics%20chemistry","高级","公开课","微积分与基础化学","为物理化学补充微积分、微分方程和线性代数。")]),
 general:t("普通化学","理解原子结构、化学键、热力学、平衡、酸碱、氧化还原和动力学。",[r("OpenStax Chemistry 2e","https://openstax.org/details/books/chemistry-2e","入门","开放教材","高中代数","免费两学期普通化学教材，例题和练习完整。"),r("MIT 5.111SC Principles of Chemical Science","https://ocw.mit.edu/courses/5-111sc-principles-of-chemical-science-fall-2014/","进阶","公开课","高中化学与代数","包含视频、讲义、习题及解答的自学型课程。"),r("MIT 5.112 Principles of Chemical Science","https://ocw.mit.edu/courses/5-112-principles-of-chemical-science-fall-2005/","高级","公开课","普通化学与微积分","以更深入的量子、热力学和结构视角学习化学原理。")]),
 organic:t("有机化学","从结构、立体化学和电子流理解反应机理与合成。",[r("Organic Chemistry with a Biological Emphasis","https://open.umn.edu/opentextbooks/textbooks/228","入门","开放教材","普通化学","开放教材，以生物分子连接官能团和机理。"),r("MIT 5.12 Organic Chemistry I","https://ocw.mit.edu/courses/5-12-organic-chemistry-i-spring-2005/","进阶","公开课","普通化学","学习结构、酸碱、取代、消除和立体化学。"),r("MIT Organic Chemistry II","https://ocw.mit.edu/search/?q=organic%20chemistry%20II","高级","公开课","有机化学 I","进入羰基、芳香体系、多步合成和光谱分析。")]),
 inorganic:t("无机与材料化学","研究周期规律、配位化学、固体结构和材料性质。",[r("Chemistry LibreTexts: Inorganic Chemistry","https://chem.libretexts.org/Bookshelves/Inorganic_Chemistry","入门","开放教材","普通化学","按主题补充周期性、晶体和配位化学。"),r("MIT 5.111SC: Transition Metals","https://ocw.mit.edu/courses/5-111sc-principles-of-chemical-science-fall-2014/","进阶","公开课","普通化学与基础量子概念","用电子结构、成键和氧化还原理解过渡金属。"),r("MIT Solid-State Chemistry","https://ocw.mit.edu/search/?q=solid-state%20chemistry","高级","公开课","无机化学、热力学与量子基础","连接晶体、缺陷、电子结构和功能材料。")]),
 physical:t("物理化学","用热力学、量子力学和动力学解释化学系统。",[r("OpenStax Chemistry 2e: Thermodynamics","https://openstax.org/books/chemistry-2e/pages/16-introduction","入门","开放教材","普通化学与代数","先建立能量、熵和自由能直觉。"),r("MIT 5.60 Thermodynamics & Kinetics","https://ocw.mit.edu/courses/5-60-thermodynamics-kinetics-spring-2008/","进阶","公开课","微积分与普通化学","系统学习热力学定律、相平衡和反应速率。"),r("MIT 5.61 Physical Chemistry","https://ocw.mit.edu/search/?q=5.61%20physical%20chemistry","高级","公开课","微积分、线性代数与基础量子","进入量子化学、光谱与分子结构。")]),
 analytical:t("分析化学与实验","学习测量、校准、误差、光谱、色谱和安全规范。",[r("Analytical Chemistry 2.1","https://chem.libretexts.org/Bookshelves/Analytical_Chemistry/Analytical_Chemistry_2.1_(Harvey)","入门","开放教材","普通化学与基础统计","免费教材，覆盖定量分析和方法验证。"),r("MIT 5.310 Laboratory Chemistry","https://ocw.mit.edu/courses/5-310-laboratory-chemistry-fall-2019/","进阶","公开课","普通化学；需要线下实验条件","包含实验技术、数据分析和报告规范。"),r("NIST Chemistry WebBook","https://webbook.nist.gov/chemistry/","高级","项目平台","分析化学与数据处理","使用权威光谱和热化学数据进行鉴定与验证。")]),
 biochem:t("生物化学与化学生物学","理解蛋白质、酶、代谢和分子识别中的化学原理。",[r("OpenStax Biology 2e: Biological Macromolecules","https://openstax.org/books/biology-2e/pages/3-introduction","入门","开放教材","普通化学","从大分子结构进入生命化学。"),r("MIT 7.05 General Biochemistry","https://ocw.mit.edu/courses/7-05-general-biochemistry-spring-2020/","进阶","公开课","有机化学与普通生物","系统学习蛋白质、酶、代谢和生物能量。"),r("MIT Chemical Biology","https://ocw.mit.edu/search/?q=chemical%20biology","高级","公开课","有机、生化与细胞生物学","用化学工具研究和操控生物过程。")]),
 projects:t("项目与进阶方向","通过安全实验、公开数据或分子计算形成可复现成果。",[r("PhET Chemistry Simulations","https://phet.colorado.edu/en/simulations/filter?subjects=chemistry&type=html","入门","项目平台","普通化学基础","改变变量并记录对平衡、酸碱或气体行为的影响。"),r("NIST Chemistry WebBook Project","https://webbook.nist.gov/chemistry/","进阶","项目平台","普通化学、统计与绘图","比较一组化合物的光谱或热化学性质。"),r("Materials Project","https://next-gen.materialsproject.org/","高级","项目平台","固体化学、量子与 Python","使用开放计算数据研究材料结构—性质关系。")]),
 books:t("书单与资源","集中查看开放教材和大学官方课程。",[])
};
export const chemistry:SubjectConfig={slug:"chemistry",name:"化学",en:"CHEMISTRY",intro:"化学研究物质的组成、结构、性质与转化，并把微观粒子模型连接到实验中可观察的变化。",caution:"化学不能只背反应。先守恒、再结构、后能量与动力学；涉及实验时必须遵守实验室安全规范，不独自进行高风险操作。",groups:[start,["基础",[["tools","学习工具"],["foundations","数学与物理基础"],["general","普通化学"]]],["大学核心",[["organic","有机化学"],["inorganic","无机与材料化学"],["physical","物理化学"],["analytical","分析化学与实验"]]],["连接与实践",[["biochem","生物化学与化学生物学"],["projects","项目与进阶方向"],["books","书单与资源"]]]],topics:chemistryTopics,phases:[{time:"1–2 个月",title:"补齐计量与原子基础",goal:"建立单位、摩尔、守恒和微观模型。",learn:"测量、化学计量、原子、周期表、化学键。",done:"能独立配平并完成定量计算。",link:"foundations"},{time:"3–5 个月",title:"完成普通化学",goal:"用结构、能量和平衡解释反应。",learn:"气体、溶液、热力学、平衡、酸碱、氧化还原、动力学。",done:"完成一套大学普通化学习题。",link:"general"},{time:"4–6 个月",title:"学习有机与无机结构",goal:"从电子和几何理解反应及材料。",learn:"官能团、机理、合成、配位、晶体和固体。",done:"能画电子流并预测基础结构性质。",link:"organic"},{time:"3–5 个月",title:"进入物理与分析化学",goal:"把定量理论连接到测量。",learn:"热力学、量子、动力学、光谱、误差和校准。",done:"完成一份带不确定度的数据报告。",link:"physical"},{time:"持续",title:"选择连接方向并实践",goal:"进入材料、生化、环境或计算化学。",learn:"数据库、模拟、文献、实验设计和安全。",done:"完成一个可复查的数据或实验项目。",link:"projects"}],tools:[["结构与数据",[["PubChem","https://pubchem.ncbi.nlm.nih.gov/","查询化合物结构与性质"],["NIST WebBook","https://webbook.nist.gov/chemistry/","检索光谱和热化学数据"],["Ketcher","https://lifescience.opensource.epam.com/ketcher/index.html","在浏览器中绘制化学结构与反应"]]],["计算与可视化",[["Avogadro","https://avogadro.cc/","开源分子建模与可视化"],["MolView","https://molview.org/","在线查看分子三维结构"],["Python","https://www.python.org/","分析实验与计算数据"]]],["文献与安全",[["Google Scholar","https://scholar.google.com/","检索化学研究"],["Zotero","https://www.zotero.org/","管理论文和引用"],["PubChem Laboratory Chemical Safety Summary","https://pubchem.ncbi.nlm.nih.gov/","检查化学品危害信息"]]]],books:[["OpenStax Chemistry 2e","https://openstax.org/details/books/chemistry-2e","普通化学 · 入门","完整免费两学期教材。"],["Organic Chemistry with a Biological Emphasis","https://open.umn.edu/opentextbooks/textbooks/228","有机化学 · 进阶","开放且重视反应机理。"],["Analytical Chemistry 2.1","https://chem.libretexts.org/Bookshelves/Analytical_Chemistry/Analytical_Chemistry_2.1_(Harvey)","分析化学 · 进阶","免费定量分析教材。"]],portals:[["MIT","MIT OCW Chemistry","https://ocw.mit.edu/search/?d=Chemistry","覆盖普通、有机、无机、物化和实验课程。"],["OpenStax","OpenStax Chemistry","https://openstax.org/subjects/science","合法免费阅读的基础教材。"],["NIST","NIST Chemistry WebBook","https://webbook.nist.gov/chemistry/","权威开放化学数据。"]]};

const engineeringTopics:Record<string,Topic>={
 tools:t("学习工具","用 CAD、仿真、编程和版本管理记录从需求到验证的全过程。",[]),
 foundations:t("工程基础","补齐微积分、线性代数、力学、电磁、概率和编程。",[r("OpenStax University Physics","https://openstax.org/details/books/university-physics-volume-1","入门","开放教材","高中代数与三角","为机械、电气和材料建立物理基础。"),r("MIT Introductory Science and Math","https://ocw.mit.edu/collections/introductory-science-and-math/","进阶","公开课","高中数学","MIT 汇总的微积分、物理、化学和编程起点。"),r("MIT Engineering Mathematics","https://ocw.mit.edu/search/?q=engineering%20mathematics","高级","公开课","微积分与线性代数","深化微分方程、变换、数值和优化方法。")]),
 design:t("工程设计与制造","从需求、约束和权衡出发，迭代构思、原型和验证。",[r("Engineering Design Process","https://engineering.mit.edu/education/engineering-design-process/","入门","公开讲义","无需前置","用问题定义、原型、测试和迭代理解设计流程。"),r("MIT 2.007 Design and Manufacturing I","https://ocw.mit.edu/courses/2-007-design-and-manufacturing-i-spring-2009/","进阶","公开课","力学、制图与基础制造","通过机器人项目完成设计、分析和制造。"),r("MIT Product Design and Development","https://ocw.mit.edu/search/?q=product%20design%20development","高级","公开课","工程设计与项目经验","进入系统架构、用户需求、经济性和团队开发。")]),
 electrical:t("电子与电气工程","学习电路、电子器件、信号、系统、电磁和能量转换。",[r("MIT 6.01SC Introduction to EECS I","https://ocw.mit.edu/courses/6-01sc-introduction-to-electrical-engineering-and-computer-science-i-spring-2011/","入门","公开课","Python、代数与基础物理","用机器人实验连接软件、信号、系统和电路。"),r("MIT 6.002 Circuits and Electronics","https://ocw.mit.edu/courses/6-002-circuits-and-electronics-spring-2007/","进阶","公开课","微积分、电磁与微分方程","系统学习电路分析、晶体管和放大器。"),r("MIT Signals and Systems","https://ocw.mit.edu/search/?q=signals%20and%20systems","高级","公开课","电路、线性代数与微分方程","进入傅里叶、采样、滤波和系统分析。")]),
 mechanical:t("机械工程","用力学、热流体和材料知识分析并设计机械系统。",[r("MIT 2.001 Mechanics & Materials I","https://ocw.mit.edu/courses/2-001-mechanics-materials-i-fall-2006/","入门","公开课","大学力学与微积分","从运动、受力和材料响应建立固体力学基础。"),r("MIT Dynamics and Control I","https://ocw.mit.edu/search/?q=dynamics%20control%20mechanical","进阶","公开课","力学、微分方程与线性代数","分析机械系统运动、振动和反馈。"),r("MIT Thermodynamics and Fluid Mechanics","https://ocw.mit.edu/search/?q=thermodynamics%20fluid%20mechanics","高级","公开课","热学、微积分与微分方程","连接能量转换、流动和机械系统设计。")]),
 computer:t("计算机工程","连接数字电路、处理器、存储、嵌入式系统和软硬件协同设计。",[r("Nand2Tetris","https://www.nand2tetris.org/","入门","项目平台","基础编程与二进制概念","从逻辑门开始逐步构建 CPU、汇编器和完整计算机系统。"),r("MIT 6.004 Computation Structures","https://ocw.mit.edu/courses/6-004-computation-structures-spring-2017/","进阶","公开课","编程、电路与离散数学","从晶体管、逻辑和状态机进入指令集、处理器与存储系统。"),r("MIT 6.823 Computer System Architecture","https://ocw.mit.edu/courses/6-823-computer-system-architecture-fall-2005/","高级","公开课","计算机组成、操作系统与数字逻辑","深入流水线、缓存、虚拟内存、多处理器和并行体系结构。")]),
 aerospace:t("航空航天工程","综合空气动力学、结构、推进、控制和轨道力学设计飞行器与航天系统。",[r("NASA Beginner’s Guide to Aeronautics","https://www.nasa.gov/stem-content/beginners-guide-to-aeronautics/","入门","公开讲义","高中代数、几何与基础物理","通过交互资料理解飞行、空气动力、喷气推进和火箭的基本原理。"),r("MIT 16.00 Introduction to Aerospace Engineering and Design","https://ocw.mit.edu/courses/16-00-introduction-to-aerospace-engineering-and-design-spring-2003/","进阶","公开课","力学、微积分与基础工程设计","以设计项目连接航空、航天、结构、推进和系统工程。"),r("MIT 16.01 Unified Engineering I–IV","https://ocw.mit.edu/courses/16-01-unified-engineering-i-ii-iii-iv-fall-2005-spring-2006/","高级","公开课","微积分、微分方程、力学与热学","系统整合流体、热力推进、材料结构、信号、控制与编程。")]),
 systems:t("控制与系统工程","研究反馈、稳定性、状态估计、优化和复杂系统集成。",[r("Feedback Systems — Åström & Murray","https://fbsbook.org/","入门","开放教材","微积分、线性代数与微分方程","作者公开教材，连接反馈直觉与数学模型。"),r("MIT 6.01SC Signals and Systems","https://ocw.mit.edu/courses/6-01sc-introduction-to-electrical-engineering-and-computer-science-i-spring-2011/pages/unit-2-signals-and-systems/","进阶","公开课","编程、电路与线性系统","学习系统响应、状态机和控制。"),r("MIT Underactuated Robotics","https://underactuated.mit.edu/","高级","公开讲义","动力学、控制、优化与编程","开放讲义深入非线性控制、规划和机器人。")]),
 materials:t("材料与结构","理解材料的结构—性能—加工关系及结构安全。",[r("MIT 3.091 Introduction to Solid-State Chemistry","https://ocw.mit.edu/courses/3-091-introduction-to-solid-state-chemistry-fall-2018/","入门","公开课","普通化学与基础物理","从原子结构进入晶体、缺陷和材料性质。"),r("MIT 3.11 Mechanics of Materials","https://ocw.mit.edu/courses/3-11-mechanics-of-materials-fall-1999/","进阶","公开课","静力学与微积分","学习应力、应变、扭转和梁弯曲。"),r("Materials Project","https://next-gen.materialsproject.org/","高级","项目平台","材料学、量子基础与数据分析","使用开放计算数据库筛选和比较材料。")]),
 projects:t("项目与进阶方向","围绕真实约束完成需求、模型、原型、测试和复盘。",[r("Arduino Project Hub","https://projecthub.arduino.cc/","入门","项目平台","基础电路与编程","从传感器或自动控制小项目开始。"),r("MIT D-Lab Resources","https://d-lab.mit.edu/resources","进阶","项目平台","工程基础与设计","关注可持续、可维护和真实用户需求。"),r("NASA Open Data Portal","https://data.nasa.gov/","高级","项目平台","建模、编程与领域知识","用公开工程数据完成建模或可靠性分析。")]),
 books:t("书单与资源","集中查看开放教材与大学工程课程。",[])
};
engineeringTopics.electrical.curriculum={basis:"参考 MIT 电气工程培养结构，将数学与编程之后的学习组织为电路、信号、电子系统、应用方向和综合实验，而不是机械式重复通用工程基础。",reference:["MIT Electrical Engineering with Computing (Course 6-5)","https://catalog.mit.edu/degree-charts/electrical-engineering-computing-course-6-5/"],stages:[
 {title:"电路与物理系统",courses:"电路分析、模拟电子、数字电子、电磁场与半导体基础",practice:"仿真并搭建一个传感器放大或电源电路。"},
 {title:"信号与系统",courses:"线性系统、傅里叶分析、概率、数字信号处理",practice:"采集真实信号，完成滤波、频谱分析与误差说明。"},
 {title:"电子与能量转换",courses:"微电子、功率电子、通信、电机与能源系统",practice:"选择一个方向完成器件或系统级设计。"},
 {title:"嵌入式与系统设计",courses:"微控制器、接口、实时系统、软硬件协同",practice:"制作包含传感、计算和执行器的闭环原型。"},
 {title:"综合实验",courses:"测量、调试、可靠性、安全与工程沟通",practice:"提交原理图、测试数据、失效分析和设计复盘。"}
]};
engineeringTopics.mechanical.curriculum={basis:"参考 MIT 机械工程本科核心，将主线放在固体、热流体、动力学、制造和实验设计，突出机械系统的建模与实体实现。",reference:["MIT Mechanical Engineering (Course 2)","https://catalog.mit.edu/degree-charts/mechanical-engineering-course-2/"],stages:[
 {title:"固体与材料力学",courses:"静力学、动力学、材料力学、机械结构",practice:"分析一个梁、支架或传动部件的载荷与变形。"},
 {title:"热力学与流体",courses:"热力学、流体力学、传热、能量转换",practice:"建立热系统或流动系统的能量平衡与仿真。"},
 {title:"动力学与控制",courses:"振动、系统动力学、传感器、反馈控制",practice:"辨识一个机械系统并设计稳定控制器。"},
 {title:"设计与制造",courses:"机械设计、CAD、公差、制造过程与选材",practice:"完成可制造的装配设计、工程图和原型。"},
 {title:"测量与产品实现",courses:"仪器、实验设计、数据分析、可靠性与成本",practice:"用实验验证性能，并迭代至少一次设计。"}
]};
engineeringTopics.computer.curriculum={basis:"参考 UIUC 计算机工程培养方案，将计算机工程明确放在电子硬件与计算机科学的交界处，主线是数字逻辑、体系结构、嵌入式系统和软硬件协同。",reference:["UIUC Computer Engineering, BS","https://catalog.illinois.edu/undergraduate/engineering/computer-engineering-bs/"],stages:[
 {title:"编程与离散基础",courses:"C/C++、数据结构、离散数学、概率与低级编程",practice:"用 C 实现数据结构并理解内存、位运算和编译过程。"},
 {title:"电路与数字逻辑",courses:"基础电路、电子学、组合逻辑、时序逻辑与 HDL",practice:"用 HDL 设计、仿真并测试一个处理器数据通路模块。"},
 {title:"计算机体系结构",courses:"指令集、流水线、缓存、虚拟内存、并行计算",practice:"实现简化 CPU 或测量程序在存储层次中的性能。"},
 {title:"嵌入式与网络系统",courses:"微控制器、实时系统、操作系统、接口与计算机网络",practice:"制作一个具备传感、通信和实时响应的嵌入式设备。"},
 {title:"硬件系统项目",courses:"验证、调试、安全、可靠性与软硬件共同设计",practice:"交付代码、原理图、测试计划和端到端演示。"}
]};
engineeringTopics.aerospace.curriculum={basis:"参考 MIT AeroAstro 的 Unified Engineering 结构，把材料结构、流体、热力推进、信号与系统先统一起来，再进入飞行动力学、控制和航空或航天设计。",reference:["MIT Aerospace Engineering (Course 16)","https://catalog.mit.edu/schools/engineering/aeronautics-astronautics/"],stages:[
 {title:"统一工程核心",courses:"材料与结构、流体力学、热力学、推进、信号与计算",practice:"为同一飞行器建立质量、载荷、能量和信息模型。"},
 {title:"空气动力与推进",courses:"可压缩流、翼型、飞行性能、燃气轮机与火箭推进",practice:"比较不同翼型或推进方案的性能与适用边界。"},
 {title:"结构与飞行动力学",courses:"轻质结构、振动、稳定性、轨道或飞行动力学",practice:"完成机翼结构、飞行稳定性或轨道任务分析。"},
 {title:"导航制导与控制",courses:"状态空间、自动控制、估计、导航与自主系统",practice:"为无人机、卫星或飞行器设计制导控制仿真。"},
 {title:"航空／航天系统设计",courses:"任务需求、系统权衡、安全、测试与适航意识",practice:"完成飞机或航天器概念设计及关键设计评审。"}
]};
engineeringTopics.systems.curriculum={basis:"参考 MIT 动态系统、控制与系统工程课程，将重点放在建模、反馈、估计、优化和跨组件集成，而非某一种实体设备。",reference:["MIT EECS — Dynamical System Modeling and Control Design","https://catalog.mit.edu/schools/engineering/electrical-engineering-computer-science/"],stages:[
 {title:"数学建模",courses:"线性代数、微分方程、概率、状态空间与系统辨识",practice:"从数据建立一个动态系统模型并验证参数。"},
 {title:"信号与动态系统",courses:"时域与频域分析、稳定性、可控性、可观性",practice:"解释模型的模态、响应速度和稳定边界。"},
 {title:"反馈控制",courses:"PID、根轨迹、频率设计、状态反馈与鲁棒性",practice:"比较两种控制器在扰动和模型误差下的表现。"},
 {title:"估计与优化",courses:"卡尔曼滤波、最优控制、约束优化、规划与决策",practice:"实现一个含噪状态估计或最优轨迹问题。"},
 {title:"系统集成",courses:"需求、接口、可靠性、安全、验证与复杂性管理",practice:"为多组件系统建立需求追踪和验证矩阵。"}
]};
engineeringTopics.materials.curriculum={basis:"参考 MIT 材料科学培养方案，以加工—结构—性能—应用关系为主轴，区别于机械工程的宏观结构分析和化学的分子反应主线。",reference:["MIT Materials Science and Engineering (Course 3)","https://catalog.mit.edu/degree-charts/materials-science-engineering-course-3/"],stages:[
 {title:"材料结构",courses:"原子键合、晶体、缺陷、相与微观组织",practice:"用结构数据或显微图解释一种材料的性质。"},
 {title:"热力学与动力学",courses:"相平衡、扩散、相变、凝固与微结构演化",practice:"计算相稳定性并分析热处理路径。"},
 {title:"材料性能",courses:"力学、电学、磁学、光学和热学性质",practice:"建立结构—性能关系并解释失效机制。"},
 {title:"加工与表征",courses:"金属、陶瓷、聚合物、复合材料加工及表征方法",practice:"设计制程和表征方案，说明测量不确定度。"},
 {title:"材料选择与研究",courses:"选材、寿命、可持续性、计算材料与实验设计",practice:"针对具体工况比较候选材料并给出验证计划。"}
]};
export const engineering:SubjectConfig={slug:"engineering",name:"工程学",en:"ENGINEERING",intro:"工程学把科学与数学转化为在约束条件下可靠工作的系统。核心不是套公式，而是需求、建模、权衡、实现、测试和迭代。",caution:"真实工程涉及安全、法规与责任。自学项目应从低风险原型开始，清楚记录假设和失效模式；高压、高温、结构承载等实验必须由专业人员指导。",groups:[start,["共同基础",[["tools","学习工具"],["foundations","工程基础"],["design","工程设计与制造"]]],["主要方向",[["electrical","电子与电气工程"],["mechanical","机械工程"],["computer","计算机工程"],["aerospace","航空航天工程"],["systems","控制与系统工程"],["materials","材料与结构"]]],["实践",[["projects","项目与进阶方向"],["books","书单与资源"]]]],topics:engineeringTopics,phases:[{time:"2–4 个月",title:"补齐数理与编程",goal:"获得分析工程系统的共同语言。",learn:"微积分、线性代数、力学、电磁、概率、Python。",done:"能建立简单系统模型并检查单位和数量级。",link:"foundations"},{time:"2–3 个月",title:"学习设计过程",goal:"从需求和约束而不是方案开始。",learn:"需求、功能分解、方案比较、制图、原型、测试。",done:"完成一个有设计记录的小型原型。",link:"design"},{time:"4–8 个月",title:"完成一个方向的核心",goal:"选择一个工程方向作为主线。",learn:"电气、机械、计算机或航空航天方向的核心课程。",done:"独立完成核心习题和一次仿真。",link:"electrical"},{time:"3–5 个月",title:"理解反馈和系统集成",goal:"分析组件连接后的动态与失效。",learn:"状态、反馈、稳定性、控制、可靠性与接口。",done:"构建并调试一个闭环系统。",link:"systems"},{time:"持续",title:"通过项目形成工程判断",goal:"在真实约束下权衡性能、成本和安全。",learn:"原型、测量、验证、文档和复盘。",done:"发布可复现的设计文件、测试结果和改进记录。",link:"projects"}],tools:[["设计与制造",[["FreeCAD","https://www.freecad.org/","开源参数化 CAD"],["KiCad","https://www.kicad.org/","开源电子设计自动化"],["Arduino","https://www.arduino.cc/","电子原型与嵌入式实践"]]],["仿真与计算",[["Python","https://www.python.org/","数值分析与自动化"],["GNU Octave","https://octave.org/","矩阵计算与系统仿真"],["LTspice","https://www.analog.com/en/resources/design-tools-and-calculators/ltspice-simulator.html","电路仿真"]]],["协作与记录",[["GitHub","https://github.com/","管理代码和设计版本"],["Jupyter","https://jupyter.org/","保存计算、图表和说明"],["Zotero","https://www.zotero.org/","管理标准、论文和资料"]]]],books:[["OpenStax University Physics","https://openstax.org/details/books/university-physics-volume-1","工程基础 · 入门","覆盖工程所需物理基础。"],["Feedback Systems","https://fbsbook.org/","控制 · 进阶","公开反馈控制教材。"],["MIT Mechanics of Materials","https://ocw.mit.edu/courses/3-11-mechanics-of-materials-fall-1999/","材料力学 · 进阶","含开放教材和习题。"]],portals:[["MIT","MIT OCW Engineering","https://ocw.mit.edu/search/?d=Engineering","电气、机械、土木、材料等完整课程。"],["OpenStax","OpenStax Science","https://openstax.org/subjects/science","工程数理基础教材。"],["MIT","MIT Open Learning Library","https://openlearning.mit.edu/courses-programs/open-learning-library","可交互学习部分工程课程。"]]};
