import type {SubjectConfig} from "./subjectTypes";
import GlobalHeader from "./GlobalHeader";
import LearningTimeline from "./LearningTimeline";
import {durationLabel,groupLabel,institutionLabel,kindLabel,levelLabel,phaseForEnglish,pick,prerequisiteLabel,resourceSummary,subjectCaution,subjectIntro,subjectLabel,topicLabel,useLanguage} from "./i18n";
const b=import.meta.env.BASE_URL,u=(p:string)=>b+p.replace(/^\//,"");
const mark=(kind:string)=>kind.includes("教材")?"book":kind.includes("讲义")||kind.includes("项目")?"paper":"course";
type Portal=readonly [string,string,string,string];
function TopicCurriculum({curriculum}:{curriculum:NonNullable<SubjectConfig["topics"][string]["curriculum"]>}){const{language}=useLanguage(),english=language==="en";return <section className="topic-curriculum"><h2>{pick(language,"核心课程地图","Core Curriculum")}</h2><p>{english?"The sequence follows the reference degree structure and combines core concepts, practice, and a final project.":curriculum.basis}</p><div className="curriculum-grid">{curriculum.stages.map((stage,index)=><article id={`curriculum-${index+1}`} key={stage.title}><span>{String(index+1).padStart(2,"0")}</span><h3>{english?`Core module ${String(index+1).padStart(2,"0")}`:stage.title}</h3><p>{english?"Study the central concepts and methods in this part of the undergraduate curriculum.":stage.courses}</p><p><b>{pick(language,"实践：","Practice: ")}</b>{english?"Complete exercises and produce a reviewable piece of work before moving on.":stage.practice}</p></article>)}</div><a className="curriculum-source" href={curriculum.reference[1]} target="_blank" rel="noreferrer">{pick(language,"参考培养方案：","Reference curriculum: ")}{curriculum.reference[0]} ↗</a></section>}
const chinesePortals:Partial<Record<string,Portal[]>>={
 biology:[["北大","北京大学：生物学概念与途径","https://www.icourse163.org/course/PKU-1002533002","从生物学史上的关键概念、实验与研究方法理解学科如何发展。"],["北大","北京大学：生物化学实验","https://www.icourse163.org/course/PKU-1449775172","以本科主干实验理解定量分析、层析、电泳、酶学和免疫学技术。"]],
 psychology:[["北大","北京大学：发展心理学","https://www.icourse163.org/course/PKU-1206624828","沿毕生发展主线学习生理、认知、人格与社会性变化。"]],
 "political-science":[["北大","北京大学：政治学概论","https://www.icourse163.org/course/PKU-1002578003","系统理解政治概念、现代国家、制度与政治学研究方法。"]],
 management:[["浙大","浙江大学：管理概论","https://www.icourse163.org/course/ZJU-19001","围绕管理者、组织、科学决策、计划、领导与控制建立系统框架。"]],
 history:[["复旦","复旦大学：《资治通鉴》导读","https://www.icourse163.org/course/fudan-1205930801","以经典史书训练语境化、史料辨析和思想史阅读方法。"]],
 chemistry:[["南大","南京大学：化学原理与测量","https://www.icourse163.org/course/NJU-1485609161","把物理化学、仪器分析、实验操作和数据处理连接起来。"],["南大","南京大学：物理化学","https://www.icourse163.org/course/NJU-1002580002","系统理解热力学、动力学、电化学和物质结构的定量基础。"]],
 engineering:[["清华","清华大学：电路原理","https://www.xuetangx.com/course/THU08061000294","从基础分析方法进入元器件、电路模型及工程应用。"],["清华","清华大学：自动控制理论","https://www.xuetangx.com/course/THU08081000909/","系统学习状态空间、稳定性、反馈与最优控制。"]],
 language:[["北大","北京大学：语言学概论","https://www.icourse163.org/course/PKU-1205727813","系统介绍语言的结构、演变、文字及其社会功能。"]],
 literature:[["复旦","复旦大学：中国现代文学名著选讲","https://www.icourse163.org/course/FUDAN-1205931801","通过代表作家的文本细读，理解现代文学的语言、叙事与历史语境。"]]
};
const portalsFor=(subject:SubjectConfig):Portal[]=>[...(chinesePortals[subject.slug]??[]),...subject.portals];

export function SubjectHeader({subject}:{subject:SubjectConfig}){return <GlobalHeader sidebarLabel={subject.name}/>}
export function SubjectSide({subject,active=""}:{subject:SubjectConfig;active?:string}){
 const {language}=useLanguage(),english=language==="en";
 const curriculum=subject.topics[active]?.curriculum;
 return <aside className="sidebar"><nav>{subject.groups.map(([group,items],groupIndex)=><section key={group}><h3>{english?groupLabel(group,groupIndex):group}</h3>{items.flatMap(([id,name])=>[
  <a className={id===active?"active":""} key={id} href={["intro","how","plan"].includes(id)?u(`${subject.slug}/#${id}`):u(`${subject.slug}/topics/${id}/`)}>{english?topicLabel(id,name):name}</a>,
  id===active&&curriculum?<div className="sidebar-curriculum" key={`${id}-curriculum`}>{curriculum.stages.map((stage,index)=><a href={`#curriculum-${index+1}`} key={stage.title}><span>{String(index+1).padStart(2,"0")}</span>{english?`Core module ${index+1}`:stage.title}</a>)}</div>:null
 ])}</section>)}</nav></aside>;
}
export function SubjectHome({subject}:{subject:SubjectConfig}){const{language}=useLanguage(),english=language==="en",name=subjectLabel(subject.slug,subject.name),phases=english?subject.phases.map((phase,index)=>({...phase,time:durationLabel(phase.time),...phaseForEnglish(phase.link,index,phase.mode)})):subject.phases;return <div className="shell"><SubjectHeader subject={subject}/><SubjectSide subject={subject}/><main><section id="intro" className="hero"><small>SELF-TAUGHT {subject.en}</small><h1>{english?`Self-Study ${name}`:`自学${subject.name}`}</h1><p>{english?subjectIntro(name):subject.intro}</p><aside>{english?subjectCaution(name):subject.caution}</aside></section><section id="how"><h2>{pick(language,"如何使用本站","How to Use This Site")}</h2><p>{pick(language,"左侧目录按照知识依赖组织。每个阶段只选择一套主资源，先理解概念与方法，再通过练习、写作、实验或项目检验学习成果。","The contents are ordered by knowledge dependencies. Choose one main resource for each stage, learn the concepts and methods, then test your understanding through exercises, writing, experiments, or projects.")}</p><div className="legend"><div><i className="resource-mark course"/><span><b>{pick(language,"公开课","Open courses")}</b><small>{pick(language,"绿色书签","Green bookmark")}</small></span></div><div><i className="resource-mark paper"/><span><b>{pick(language,"讲义与项目","Notes & projects")}</b><small>{pick(language,"红色书签","Red bookmark")}</small></span></div><div><i className="resource-mark book"/><span><b>{pick(language,"书籍与教材","Books & textbooks")}</b><small>{pick(language,"蓝色书签","Blue bookmark")}</small></span></div></div></section><section id="plan"><h2>{pick(language,"学习规划","Study Plan")}</h2>
<p className="plan-intro">{english?`The goal is an undergraduate-equivalent education in ${name}: master the core, continue into current fields, and apply what you learn through projects or research. Times assume 6–10 hours per week.`:`目标是完成相当于本科${subject.name}专业教育的系统训练：掌握完整的核心知识，能够继续学习前沿领域，并通过项目或研究应用所学。以下时间按每周 6–10 小时估算。`}</p>
<div className="beginner-note"><strong>{pick(language,"判断自己是否真正学会","How to tell whether you really learned it")}</strong><ul><li>{pick(language,"能不用原文，用自己的语言解释核心概念。","Explain the central ideas in your own words without copying the source.")}</li><li>{pick(language,"能独立完成习题、分析材料或小型项目。","Complete exercises, analysis, or a small project independently.")}</li><li>{pick(language,"能指出方法的假设、证据来源与适用边界。","State the assumptions, evidence, and limits of a method.")}</li></ul></div><LearningTimeline phases={phases}/><div className="plan-steps">{phases.map((p,index)=><article key={p.title}><div className="phase-meta"><span>{String(index+1).padStart(2,"0")}</span><small>{pick(language,"建议用时","Suggested time")}<br/><b>{p.time}</b></small></div><div><h3>{p.title}</h3><p className="phase-goal">{p.goal}</p><dl><div><dt>{pick(language,"主要学习内容","What to learn")}</dt><dd>{p.learn}</dd></div><div><dt>{pick(language,"完成标志","Completion check")}</dt><dd>{p.done}</dd></div></dl><a href={u(`${subject.slug}/topics/${p.link}/`)}>{pick(language,"进入相关章节 →","Open related chapter →")}</a></div></article>)}</div></section></main></div>}
export function SubjectTopicPage({subject,topicSlug}:{subject:SubjectConfig;topicSlug:string}){const{language}=useLanguage(),english=language==="en",topic=subject.topics[topicSlug],title=topicLabel(topicSlug,topic?.title??topicSlug);if(!topic)return <main><h1>{pick(language,"页面不存在","Page not found")}</h1></main>;return <div className="shell"><SubjectHeader subject={subject}/><SubjectSide subject={subject} active={topicSlug}/><main><section className="hero"><small>SELF-TAUGHT {subject.en} / {english?title:topic.title}</small><h1>{english?title:topic.title}</h1><p>{english?`Build a working understanding of ${title} through selected open courses, textbooks, and practical work.`:topic.intro}</p></section>{topic.curriculum&&<TopicCurriculum curriculum={topic.curriculum}/>} {topicSlug==="tools"?<div className="tool-sections">{subject.tools.map(([group,items],index)=><section key={group}><h2>{english?`Tool set ${String(index+1).padStart(2,"0")}`:group}</h2><div className="tool-list">{items.map(([name,url,note])=><p key={name}><a href={url} target="_blank" rel="noreferrer">{name}</a><span>{english?`: Use ${name} as part of a reliable learning and project workflow.`:`：${note}`}</span></p>)}</div></section>)}</div>:<section><h2>{pick(language,"分级精选资源","Selected Resources by Level")}</h2><div className="cards">{topic.resources.map(x=><article className="card" key={x.name}><i className={`resource-mark ${mark(x.kind)}`}/><div><small>{english?`${kindLabel(x.kind)} · ${levelLabel(x.level)}`:`${x.kind} · ${x.level}`}</small><h3><a href={x.url} target="_blank" rel="noreferrer">{x.name}</a></h3><p>{english?resourceSummary(x.name,title,x.kind):x.description}</p><dl><div><dt>{pick(language,"难度","Level")}</dt><dd>{english?levelLabel(x.level):x.level}</dd></div><div><dt>{pick(language,"前置要求","Prerequisites")}</dt><dd>{english?prerequisiteLabel(x.level):x.pre}</dd></div></dl></div></article>)}</div></section>}</main></div>}
export function SubjectBooksPage({subject}:{subject:SubjectConfig}){const{language}=useLanguage(),english=language==="en",name=subjectLabel(subject.slug,subject.name);return <div className="shell"><SubjectHeader subject={subject}/><SubjectSide subject={subject} active="books"/><main><section className="hero"><small>SELF-TAUGHT {subject.en} / {pick(language,"书单与资源","BOOKS & RESOURCES")}</small><h1>{pick(language,"书单与资源","Books & Resources")}</h1><p>{pick(language,"优先收录可以合法免费阅读的教材、原始资料和大学官方公开课程。先选一套主资源，再用其他材料补充视角。","Priority is given to legally accessible open textbooks, primary materials, and official university courses. Choose one main resource, then use the others for additional perspectives.")}</p></section><section><h2>{pick(language,"公开电子书","Open Books")}</h2><div className="library-list">{subject.books.map(([book,url,tag,text])=><article key={book}><i className="resource-mark book"/><div><small>{english?`Open resource · ${name}`:tag}</small><h3><a href={url} target="_blank" rel="noreferrer">{book}</a></h3><p>{english?`An open learning resource selected for the ${name} path.`:text}</p></div></article>)}</div></section><section><h2>{pick(language,"公开课程与资料入口","Open Courses & Resource Portals")}</h2><p className="section-note">{pick(language,"中文资源仅选择学科实力突出且课程材料可公开访问的顶尖高校；课程轮次结束后，部分平台仍可继续自学。","Chinese-language resources are limited to leading universities with publicly accessible materials. Some platforms remain available for self-study after a course run ends.")}</p><div className="course-portals">{portalsFor(subject).map(([tag,portal,url,text])=><article key={portal}><span>{english?institutionLabel(tag):tag}</span><h3><a href={url} target="_blank" rel="noreferrer">{portal}</a></h3><p>{english?`An official course or resource portal selected for ${name}.`:text}</p></article>)}</div></section></main></div>}
