import {topics} from "./data";import {Header,Side} from "./Home";
import {kindLabel,levelLabel,pick,prerequisiteLabel,resourceSummary,topicLabel,useLanguage} from "./i18n";
const toolGroups=[
 {title:"数据与分析工具",intro:"用于整理数据、建立模型、完成统计分析与可视化。",items:[{name:"Microsoft Excel",url:"https://www.microsoft.com/microsoft-365/excel",note:"财务报表、估值模型与快速分析"},{name:"Google Sheets",url:"https://workspace.google.com/products/sheets/",note:"在线表格与团队协作"},{name:"Python",url:"https://www.python.org/",note:"数据清洗、分析、可视化和自动化"},{name:"R",url:"https://www.r-project.org/",note:"统计分析与计量经济学"},{name:"Jupyter",url:"https://jupyter.org/",note:"整合代码、推导、图表与研究结论"}]},
 {title:"论文与研究工具",intro:"用于检索、阅读、管理和追踪学术资料。",items:[{name:"Google Scholar",url:"https://scholar.google.com/",note:"检索论文、作者及引用关系"},{name:"Zotero",url:"https://www.zotero.org/",note:"收集论文、教材并自动管理引用"},{name:"Connected Papers",url:"https://www.connectedpapers.com/",note:"通过可视化关系发现相关论文"},{name:"Semantic Scholar",url:"https://www.semanticscholar.org/",note:"搜索论文并快速了解引用脉络"},{name:"SSRN",url:"https://www.ssrn.com/",note:"查找金融、经济与社会科学工作论文"}]},
 {title:"AI 辅助工具",intro:"用于解释概念、梳理文献和辅助代码；重要结论必须回到原始资料核验。",items:[{name:"ChatGPT",url:"https://chatgpt.com/",note:"解释概念、制定学习计划与辅助编程"},{name:"Claude",url:"https://claude.ai/",note:"长文阅读、资料整理与写作反馈"},{name:"Perplexity",url:"https://www.perplexity.ai/",note:"带来源链接的资料搜索与初步调研"},{name:"NotebookLM",url:"https://notebooklm.google/",note:"围绕自己上传的论文和教材提问"},{name:"Elicit",url:"https://elicit.com/",note:"辅助文献检索、筛选与证据整理"}]},
 {title:"知识管理工具",intro:"用于记录概念、公式、疑问和课程进度。",items:[{name:"Obsidian",url:"https://obsidian.md/",note:"本地 Markdown 笔记与双向链接"},{name:"Notion",url:"https://www.notion.com/product",note:"在线笔记、数据库和学习计划"},{name:"GitHub",url:"https://github.com/",note:"保存代码、项目和可复现研究"}]},
 {title:"金融与经济数据源",intro:"优先使用原始数据，并记录指标口径、发布时间和版本。",items:[{name:"FRED",url:"https://fred.stlouisfed.org/",note:"宏观经济与金融时间序列"},{name:"World Bank Open Data",url:"https://data.worldbank.org/",note:"全球发展与宏观经济数据"},{name:"IMF Data",url:"https://www.imf.org/en/Data",note:"国际宏观、财政与金融数据"},{name:"SEC EDGAR APIs",url:"https://www.sec.gov/search-filings/edgar-application-programming-interfaces",note:"以 API 获取美国上市公司申报与 XBRL 数据"},{name:"BIS Data Portal",url:"https://data.bis.org/",note:"国际银行、信贷、外汇、支付与全球流动性数据"}]},
 {title:"前沿专题数据",intro:"用于市场结构、气候风险和金融稳定等专题研究；使用前先阅读方法和口径说明。",items:[{name:"SEC Market Structure Data",url:"https://www.sec.gov/data-research/market-structure-data",note:"美国股票市场交易、执行质量和结构指标"},{name:"NGFS Scenarios Portal",url:"https://www.ngfs.net/ngfs-scenarios-portal/explore/",note:"气候转型与物理风险情景数据"},{name:"IMF Climate Change Indicators",url:"https://data.imf.org/en/datasets/IMF.STA%3ACCI",note:"气候、能源、排放与绿色金融指标"},{name:"BIS Innovation Hub",url:"https://www.bis.org/about/bisih/",note:"支付、数字货币与监管科技公开项目"}]}
];
export default function TopicPage({slug}:{slug:string}){const{language}=useLanguage(),english=language==="en",t=topics[slug],title=topicLabel(slug,t?.title??slug);if(!t)return <main><h1>{pick(language,"页面不存在","Page not found")}</h1></main>;const isTools=slug==="tools";return <div className="shell"><Header/><Side active={slug}/><main><section className="hero"><small>SELF-TAUGHT FINANCE / {english?title:t.title}</small><h1>{english?title:t.title}</h1><p>{english?`Build a working understanding of ${title} through selected open courses, books, data, and practical work.`:t.intro}</p></section>{isTools&&<div className="tool-sections">{toolGroups.map((g,index)=><section key={g.title}><h2>{english?`Tool set ${String(index+1).padStart(2,"0")}`:g.title}</h2><p>{english?"Use these tools to build a reliable, reproducible learning and research workflow.":g.intro}</p><div className="tool-list">{g.items.map(x=><p key={x.name}><a href={x.url} target="_blank" rel="noreferrer">{x.name}</a><span>{english?`: Use ${x.name} for learning, analysis, research, or project work.`:`：${x.note}`}</span></p>)}</div></section>)}</div>}{!isTools&&<section><h2>{pick(language,"分级精选资源","Selected Resources by Level")}</h2><div className="cards">{t.resources.map(x=><article className="card" key={x.name}><i className={`resource-mark ${x.kind?.includes("论文")?"paper":x.kind?.includes("教材")?"book":"course"}`} aria-hidden="true"/><div><small>{english?`${kindLabel(x.kind)} · ${levelLabel(x.level)}`:`${x.kind} · ${x.level}`}</small><h3><a href={x.url} target="_blank" rel="noreferrer">{x.name}</a></h3><p>{english?resourceSummary(x.name,title,x.kind):x.description??"适合该阶段系统学习，优先使用官方课程或原始资料，并通过练习检验理解。"}</p><dl><div><dt>{pick(language,"难度","Level")}</dt><dd>{english?levelLabel(x.level):x.level}</dd></div><div><dt>{pick(language,"前置要求","Prerequisites")}</dt><dd>{english?prerequisiteLabel(x.level):x.pre}</dd></div></dl></div></article>)}</div></section>}</main></div>}
